setup.py
- removed versions
- cleaned packages
- Cython support
=> Improved packaging

setup.py, tofu/geom/_GG02.pyx, tofu/geom/_GG03.pyx, tofu/geom/_basic_geom_tools.pxd, tofu/geom/_basic_geom_tools.pyx, tofu/geom/_distance_tools.pxd, tofu/geom/_raytracing_tools.pxd, tofu/geom/_sampling_tools.pxd
=> Fixing issue 89

.travis.yml, setup.py, tofu/geom/_vignetting_tools.pyx
Reverts ToFuProject/tofu#123
Revert because compilation issue not fixed yet on Cent OS 6.9
=> Revert "Issue122 pointer cpp"

setup.py, tofu/data/_core.py, tofu/geom/_GG02.pyx, tofu/geom/_GG03.pyx, tofu/geom/_core.py, tofu/geom/utils.py
Here are some fixes after working for a couple of hours on #95 
@lasofivec @Didou09 Could you please test whether these modifications run locally under your environment?
Thanks.
Florian
=> Fix setup.py for Windows as well as tests

tofu/geom/_GG02.pyx, tofu/geom/_GG03.pyx, tofu/geom/_sampling_tools.pxd, tofu/geom/_sampling_tools.pyx
Cleaned LOS_calc_signal:
---------------------------
1. Created inline function to avoid repetition of code
2. Created an array of resolutions for each LOS even if it is the same resolution for all LOS
3. Elminated useless variables
4. Renamed variables (trying to imporve PEP8 guidelines #30 )
Bug fix
--------
* When sampling lines, there were some reallocs inside of parallel loops, this cannot be done.
Now fixed
Fixes #138
=> Issue138 calc signal

tofu/geom/_sampling_tools.pyx, tofu/tests/tests01_geom/tests03_core.py
Similar to last pull request:
* Solved bug when computing get_sample with relative step.
* Unit tests to take into account variant resolution for each los
=> [bug-fix] get_sample w/relative step update unit tests

tofu/geom/_core.py, tofu/version.py
Fixes, in devel, Issue #186 
The assert was on lc, not on Types
=> [Issue 186] the assert was on lc, not Types

requirements.txt
Solves Issue #250 
Added `requirements.txt`
I tried on a new conda environment with python=3.7 and the latest pip installed.
=> [Issue #250] added requirements.txt

tofu/__init__.py, tofu/imas2tofu/__init__.py, tofu/mag/__init__.py
The origin PR on devel (#244 ) had been closed without being merged (by mistake I think)
This was corrected this morning
We now need to update master too.
This will come into a 1.4.2-alpha2
=> Less verbose warnings for missing sub-packages

Notes_Upgrades/meetings/nov_2019.md, Notes_Upgrades/meetings/nov_2019.rst
File containing agenda and summary of meeting on the 27th of November 2019
=> November meeting summary

tofu/imas2tofu/_core.py, tofu/version.py
Main Changes:
* Minor bug correction to allow MultiIDSLoader.add_ids() to work with ids handle (instead of char str) and isget=True
Issues:
-------
Fixes, in devel, issue #316
=> Issue316 common idd for all id sget

Notes_Upgrades/Communications/SeminaireStras20/2019_LM_SeminaireStras.bib, Notes_Upgrades/Communications/SeminaireStras20/2019_LM_SeminaireStras.tex, Notes_Upgrades/Communications/SeminaireStras20/figures
Added slides and sources to strasbourg seminar
=> [Communications] added strasbourg seminars

tofu/geom/_core.py
Motivation:
-------------
An error occured (cf. issue #347) on travis for a build, specifying that a config instance was missing a Struct of the subclass StructIn.
The source of this error could not be found, and it does not seem reproducible, as another push of the same branch, with a more explicit error message, did not trigger the error again (all builds successful).
As a result, the associated issue is closed (until it shows up again), and this PR simply aims at implementing a more explicit error message to help debug if this issue pops up again in the future.
Main changes:
Cleaner code and better error message in the incrimated method
Issues:
-------
Issue #347 is closed until further notice
=> Better error message for issue #347

.travis.yml
I think because of the fact the `conditions` were separated for the `master` branch, travis still tried to deploy with `bdist` for linux machines. To avoid any confusion I put both instructions in one line.
Solves #366
=> Travis bdist deployment on master

MANIFEST.in
Solves issue #377 
Added the input geometry files in the MANIFEST.in
=> [Issue #377] added geom input files in manifest

scripts/_dparser.py, tofu/entrypoints/_def.py, tofu/entrypoints/tofucalc.py, tofu/entrypoints/tofuplot.py, tofu/utils.py, tofu/version.py
Main changes:
* `tofuplot `raised an error sayign that _TOFUPATH was not defined, corrected
* `tofuplot -i magfieldlines` was bugged and did not allow to choose the number of traces and was plotting each half-trace with a different color and with non-consistent colors on various axes, fixed
=> tofu bash debugged for tofuplot and calc + better handling of magfieldlines

setup.py, tofu/geom/_core.py, tofu/tests/tests01_geom/tests03_core.py
Main changes:
* Minor changes to make error messages more informative and to add some comments in tofu/tests/tests01_geom/tests03_core.py
* Corrected a typo in setup.py that was preventing the proper directory (tests/tests01_geom/tests03_core_data/) to be included in the sdist package, leading to missing data for tests to run correctly
Issues:
----------
Fixes, in devel, issue #409
=>  bug tests4 conda forge

scripts/_dparser.py, tofu/entrypoints/_def.py, tofu/entrypoints/tofuplot.py, tofu/geom/_core.py, tofu/utils.py, tofu/version.py
Main changes:
* Config now has methods:
- `Config.from_SOLEDGE3X()` to load a tofu config from a SoLEDGE3X-compatible file format
- `Config.to_SOLEDGE3X()` to save the config into a SOLEDGE3X-compatible file format
* tofuplot now has:
- `tofuplot -i config`   : display list of available configs
- `tofuplot -i config -c XXX`: plot the specified config XXX
- `tofuplot -i config -c XXX -tosoledge3x <path>` : to plot and save the config in SOLEDGE3X format in specified path
Issues:
-------
* Fixes, in devel, issue #411
=> Issue411 config from soledge3 x

.travis.yml, scripts/tofucustom.py, scripts/tofuversion.py, tofu/version.py
Main changes:
Added temporary sys.path changes to tofuversion.py and tofucustom.py to make sure they work as standalone even when not called through tofu common bash command and installed with pip.
Issues:
-------
* Fixes, in devel, issue #416
=> Issue416 old bash commands

tofu/data/_core.py, tofu/data/_plot.py, tofu/geom/utils.py, tofu/imas2tofu/__init__.py, tofu/imas2tofu/_comp.py, tofu/imas2tofu/_comp_toobjects.py, tofu/imas2tofu/_core.py, tofu/version.py
Main changes:
* `tf.geom.utils._create_config_testcase()` can now take user-provided dict and path, default args set inside function
* `Multi.to_Plasma2d()` only adds 2dmesh shortcuts which are valid shortcuts for a given ids
* `import tofu` doesn't throw a warning if only  tha backup imas version exists alongside the current one
* Some errors have a more complete error message
Issues:
-------
* Fixes, in devel, issue #424
=> Issue #424 Minor debugging for flexibility

release_notes/release_notes_149.rst, tofu/imas2tofu/_core.py, tofu/imas2tofu/_def.py
Main changes:
* All imas2tofu defaults parameters are now in imas2tofu/_def.py so the user can customize them
Issues:
---------
* Fixes, in devel issue #433
=> Issue #433 imas2tofu default parameters

tofu/data/_plot.py, tofu/version.py
Main Changes:
* kwdargs vmin, vmax were not taken into acccount by function tf.data._plot._DataCam12D_plot() because their input value was overwritten inside the function
* It is corrected and kwdargs vmin_map and vmax_map are also set to vmin, vmax by default
Issues:
--------
Fixes, in devel, issue #446
=> Issue #446 Data.plot() takes into account vmin , vmax

tofu/geom/_core.py
Motivations:
* See issue #465 
* Was maybe related to issue #459 ?
Main changes:
* `Rays.get_indStruct_computeInOut()` is not a property anymore but a method
It returns 2 arrays of indices (`indIn` and `indOut`) instead of one (`indStruct`: can be retrieved by concatenating the two)
It can natively include only a unique `StructIn` (as required by `Rays._prepare_inputs_kInOut()`)
* `Rays._prepare_inputs_kInOut()` has been corrected:
To handle the changes mentioned above
And because the bug was coming from the wrong indexation of lists of structures
The bug is now fixed, and it does indeed also fix the so-called camera inversion mentionned in issue #459 
Example:
------------
``` …
```
=> Issue #465: Wrong indexing of Struct touched by Rays

tofu/utils.py, tofu/version.py
The interactivity had been lost due to minor typos introduced by PR #456 
Sadly the figure interactivity is something quite difficult to test in unit tests.
Issues:
-------
* Fixes, in devel, issue #490
=> [#490] Fixed bug introduced by PR #456

tofu/openadas2tofu/_read_files.py, tofu/openadas2tofu/_requests.py, tofu/tests/tests03_openadas/test_03_core.py, tofu/version.py
Motivations:
--------------
* The openadas2tofu module is working fine, but it could be bot more robust vs the needs of the user, who may not want to specify a list of element of charges in order to load all available elements / charges.
* Also, he might want to only exclude some element charges
Main changes:
* Can load all element with `element=None`
* Can load all charges with `charges=None`
* Can load all element specified in a list
* Can all all charges specified in a list
* Can load all elements except some specified in a tuple
* Can load all charges except some specified in a tuple
* Better error messages
* Better unit tests
Issues:
--------
* Fixes, in ddvel, issue #503 
Examples:
-----------
``` …
```
=> Issue503 openadas more robust

tofu/nist2tofu/_requests.py
Same problem as openadas2tofu on ITER, same solution (see #508 )
=> [#509] nist2tofu for ITER

tofu/geom/_comp_solidangles.py, tofu/geom/_core.py, tofu/geom/_plot.py, tofu/tests/tests01_geom/test_03_core.py, tofu/tests/tests01_geom/test_04_sampling.py, tofu/version.py
Motivation:
------------
* @lasofivec implemented a low-level parallelized function to compute the toroidal integral of the solid angle subtened by a 491spherical particle from all points in the torus (cf. PR #491 )
* A new method is added to Config to use this new function, to make it easy for the user, who can choose the spatial resolution, and get a plot of the result
* Units tests are updated to test this method
* This new method is quite easy to handle and the plotting can be used for debugging
Issues:
-------
* This fixes, in devel, issue #529 
* A new issue may have to be created due to strange results obtained in some cases
Example:
----------
``` …
```
=> [Issue529] Created Config.calc_solidangle_particle_integrated()

tofu/data/__init__.py, tofu/data/_check_inputs.py, tofu/data/_core_new.py, tofu/data/_mesh.py, tofu/data/_mesh_bsplines.py, tofu/data/_mesh_checks.py, tofu/data/_mesh_comp.py, tofu/data/_mesh_plot.py, tofu/tests/tests02_data/test_04_core_new.py, tofu/tests/tests06_mesh/test_01_checks.py, tofu/version.py
Motivation:
-------------
* Use the new generic `DataCollection` class to create a `Mesh2DRect` class for handling d rectangular meshes and bsplines
Main changes:
* `Mesh2DRect` class is created with the following key methods (operational and unit tested):
* `Mesh2DRect.add_mesh()`       :   add a rectangular mesh
* `Mesh2DRect.from_Config()`    : create a mesh instance from a config
* `Mesh2DRect.add_bsplines()`   : add bsplines on desired mesh
* `Mesh2DRect.get_profiles2d()` : get dict of 2d profiles, with corresponding bsplines keys
* `Mesh2DRect.select_ind()`        : select the desried 
* `Mesh2DRect.select_mesh_elements()` : select desired mesh elements (cents, knots, with neighbours)
* `Mesh2DRect.select_bsplines()`             : select desired bsplines
* …
=> Issue544 mesh2d rect

tofu/data/_mesh.py, tofu/data/_mesh_bsplines.py, tofu/data/_mesh_bsplines_operators.py, tofu/data/_mesh_comp.py, tofu/version.py
Motivations:
--------------
* For inversions , a non-centered gradient is more relevant to avoid alternating solutions (see issue #569)
Main changes:
* In `tofu/data/_mesh_bsplines_operators.py`:
* implemented `_D1_Deg0(centered=None)`  to choose between centred and non-centered gradient (default to False)
* Propagated upward to `Mesh2D.add_bsplines_operator(centered=None)`
Issues:
--------
* Fixes, in devel, issue #569 
Example:
----------
Go to `inputs_temp/`, then
```
In [1]: import tofu_inversions_ITER_ITPA_2021                                                                                                                                                                   
/Home/DV226270/ToFu_All/tofu_git/tofu/tofu/data/_inversions_comp.py:20: UserWarning: Consider …
```
=> Non-centered deg=0 D1

tofu/imas2tofu/_def.py, tofu/version.py
Main changes:
* Added more `summary` shortcuts (neutrons + runaways) and one `core_profiles` shortcut for `Ti`
=> Issue621 ids summary2 imas

tofu/geom/_core_optics.py, tofu/spectro/_fit12d_dextract.py, tofu/version.py
Main changes:
* Implemented `Cryst.get_phi_from_magaxis_summit()`
* User can set `fit2d_dextract(amp_on_bck_thresh=...)` (2 by default)
=> Issue539 fit2d

tofu/data/_mesh_bsplines_operators_rect.py, tofu/tests/tests07_inversions/test_01_isotropic.py, tofu/version.py
Main changes:
* Included tomotok algorithms in unit tests
* Fails for Algebraic methods requiring cholesky factorization of derivative matrix for deg = 0 and D1N2 (tolerated)
Issues:
---------
* Fixes, in devel, issue #617 
* D1N2 for deg = 0 to be double-checked ?
=> [#617] Unit tests for tomotok

.gitignore, tofu/data/_core.py, tofu/imas2tofu/_def.py, tofu/spectro/_fit12d.py, tofu/spectro/_fit12d_dextract.py, tofu/spectro/_fit12d_dinput.py, tofu/version.py
Main changes:
Regarding `tofu.spectro`:
* Option `fit2d_dinput(return_raw_data=...)` enabled
* Added `xtol`, `ftol`, `gtol` to `dfit1d` and `dfit2d`
* Updated `MultiIDSLoader` with `spectrometer_x_ray_crystal` with `Te`, `Ti`, `vi`, `rhotn_sign`, `data_raw`, `LOS` and `code.parameters`
=> Polish XICS

requirements.txt, setup.py, tofu/data/_mesh_comp.py, tofu/geom/_plot_optics.py, tofu/tests/tests06_mesh/test_01_checks.py
Main changes:
* Replaced `mcontour` by `contourpy` in `tofu`
* Added `contourpy` to dependencies in `setup.py` and `requirements`
=> Issue685 contour py

tofu/data/_class2_Rays.py, tofu/data/_class2_compute.py, tofu/data/_class5_compute.py, tofu/data/_class5_coordinates.py, tofu/data/_class5_projections.py, tofu/data/_class5_reflections_pts2pt.py, tofu/data/_class5_reflections_ptsvect.py, tofu/data/_class8_equivalent_apertures.py, tofu/data/_class8_etendue_los.py, tofu/data/_class8_plot.py, tofu/data/_mesh_checks.py, tofu/data/_utils_surface3d.py
Main changes:
---------------------
* `sample_rays(mode='abs', segment=int)` implemented
* Debugged `Cylindrical` crystal when axis of curvature is second (always return p0, p1)
* Debuggued `Cylindrical` crystal regarding `nin` computation in `_get_Dnin_from_k_cyl()` (sign was not +/- unity)
* Debuggued `Spherical` crystal regarding `nin` computation in `_get_Dnin_from_k_sph()` (sign was not +/- unity)
* Implemented Convex 'Cylindrical' and `Spherical` by implementing negative radius of curvature
Issues:
--------
* Fixes, in devel, issues #690, #692
Tests:
------
* convex cylindrical crystal successfully tested, spherical to be tested
=> Issue690 convex crystal + sample rays

tofu/spectro/_fit12d_dinput.py
=> Issue698 minor spectro fit12d bug

pyproject.toml, requirements.txt, setup.py, tofu/data/_class2_Rays.py, tofu/data/_class2_check.py, tofu/data/_class7_Camera.py, tofu/data/_class7_compute.py, tofu/data/_class8_Diagnostic.py, tofu/data/_class8_check.py, tofu/data/_class8_compute.py, tofu/data/_class8_etendue_los.py, tofu/data/_class8_plot.py
Main changes:
* `datastock >= 0.0.21`
* `Diagnostic.move_diagnostic_to()` implemented
* `Diagnostic.add_camera_pinhole()` implemented
* `Diagnostic.remove_diagnostic()` implemented
* `Diagnostic.remove_rays()` implemented
Issues:
---------
* Fixes, in devel, issues:
* #700 
* #702 
* #703
=> Issue700 move diag to

tofu/data/_class8_Diagnostic.py, tofu/data/_class8_check.py, tofu/data/_class8_compute.py, tofu/data/_class8_los_data.py, tofu/data/_class8_move.py, tofu/geom/_comp_solidangles.py
Main changes:
* `Diagnostic.compute_diagnostic_solid_angle()` implemented
Issues:
----------
Fixes, in devel, issue #705 
Examples:
--------------
Preliminary: create a diagnostic with two 1d pinhole cameras on WEST
```
In [2]: import tofu as tf
In [3]: conf = tf.load_config('WEST-V0')
In [4]: coll = tf.data.Diagnostic()
In [5]: coll.add_camera_pinhole(key='c0', key_diag='d0', focal=0.1, pix_nb=10, pix_size=1e-3, pinhole_radius=1e-3, compute=False)
In [6]: coll.add_camera_pinhole(key='c1', key_diag='d0', focal=0.05, tilt=np.pi/2, pix_nb=10, pix_size=1e-3, pinhole_radius=1e-3, config=conf)
Computing etendue / los for diag 'd0':
- camera 'c0': pixel 10 / 10
/home/didier/Documents/Projects/tofu/tofu/data/_class8_etendue_los.py:585: RuntimeWarning: All-NaN slice …
```
=> Issue705 solid angle

tofu/data/_class2_compute.py, tofu/data/_class8_Diagnostic.py, tofu/data/_class8_los_data.py, tofu/tests/tests00_root/test_03_plot.py, tofu/tests/tests01_geom/test_02_compute.py, tofu/tests/tests01_geom/test_03_core.py, tofu/tests/tests01_geom/test_04_core_optics.py, tofu/tests/tests01_geom/test_05_solid_angles.py, tofu/tests/tests02_data/test_03_core.py, tofu/tests/tests02_data/test_04_spectrallines.py, tofu/tests/tests03_openadas/test_03_core.py, tofu/tests/tests04_spectro/test_01_fit12d.py, tofu/tests/tests04_spectro/test_02_analysistools.py, tofu/tests/tests04_spectro/test_03_rockingcurve.py, tofu/tests/tests05_nist/test_03_core.py, tofu/tests/tests06_mesh/test_01_checks.py, tofu/tests/tests07_inversions/test_01_isotropic.py, tofu/tests/tests08_diagnostics/test_01_diagnostics.py, tofu/tests/tests09_tutorials/test_01_runall.py
Main changes:
* `Diagnostic.sample_rays(return_coords='ang_vs_phi')` implemented
* `Diagnostic.plot_diagnostic_interapolated_along_los(key_data_y='ang_vs_ephi', vmin=float, vmax=float)` implemented
Issues:
--------
* Fixes, in devel, issue #711 
Examples:
-----------
=> Issue711 angle at radius rays

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_los_data.py
Main changes:
* `val_out` bug fixed in `_interpolated_along_los()`
Issues:
-------
* Fixes, in devel, issue #717
=> [#717] bug fixed

tofu/data/_class10_checks.py, tofu/data/_class10_compute.py, tofu/data/_class10_refs.py, tofu/data/_class9_compute.py, tofu/geom/_core.py, tofu/imas2tofu/_comp_toobjects.py, tofu/spectro/_fit12d_dextract.py, tofu/spectro/_fit12d_dinput.py
Main changes:
------------------
* Debugged dratio and dshift
* added bcki to dextract
* Replaced Plasma2D by Collection
* better handling of common ref in _class10_refs.py
* debugged geometry matrix resizing
=> Issue761 imas2tofu error

tofu/data/_class5_projections.py, tofu/data/_class5_reflections_pts2pt.py, tofu/data/_class8_equivalent_apertures.py
Main changes:
* Minor things forgotten from PR #778 
* More robust and accurate reflection computation in concave cylindrical mirror using deg 3 fit
=> Issue776 strict aperture

tofu/data/_utils_surface3d.py, tofu/spectro/_spectralrange2d.py
Main changes:
* `spectro.spectral_range2d()` debugged and plots more info + better docstr
Issues:
----------
Fixes, in devel, issue #789
=> Issue789 better spectral range2d

tofu/data/_class5_projections.py, tofu/data/_class5_reflections_pts2pt.py, tofu/data/_class5_reflections_ptsvect.py, tofu/data/_class8_equivalent_apertures.py
Main changes
* Fixed inversion of dtheta and psi in the following routines:
- `reflection_pts2pts()`
- `reflection_ptsvect()`
* Fixed solver for concave spherical crystals - more robust and accurate 
Issues:
-------
Fixes, in devel, issue #791
=> Issue791 spherical inverted

tofu/data/_class08_Diagnostic.py, tofu/data/_class5_projections.py, tofu/data/_class8_compute_signal.py, tofu/data/_class8_equivalent_apertures.py, tofu/data/_class8_los_angles.py, tofu/data/_class8_vos.py, tofu/tests/tests09_tutorials/tuto_real0.py
Main changes:
Issues:
--------
Fixes, in devel, issue #792
=> Issue792 los binning

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_plot_vos_spectro.py, tofu/data/_class8_reverse_ray_tracing.py, tofu/data/_class8_vos.py, tofu/data/_class8_vos_spectro.py, tofu/data/_class8_vos_spectro_nobin_at_lamb.py
Main changes:
* compte_diagnostic_vos_nobin_at_lamb() implemented
Issues:
--------
Fixes, in devel, issue #805 
Examples:
-----------
=> Issue805 some wavelengths

tofu/data/_class10_algos.py, tofu/data/_class10_compute.py
Main changes:
* Minimum iterations = 3
* Better normalization of geometry matrix + normalization printed
Issues:
--------
Fixes, in devel, issue #818
=> Issue818 convegence

requirements.txt, setup.py, tofu/data/_class01_Plasma2D.py
Main changes:
* Compatibility with `bsplines2d` 0.0.6
Issues:
-------
Fixes, in devel, issue #820
=> [#devel] Updated dependencies to bsplines2d 0.0.6

tofu/data/_DataCollection_check_inputs.py, tofu/data/_core.py, tofu/data/_spectrallines_checks.py, tofu/data/_spectralunits.py
Main changes:
* Removed references to `np.int` and `np.float`
=> Removed usage of np.int and np.float

tofu/data/_class10_compute.py
Main changes:
Debugged `ist_mat` and `ist_prof` using a custom `dict` comprehension from `dref_vector`
Issues:
-------
Fixes, in devel, issue #825
=> [#825] custom dref_vector for matrix and profile_2d

tofu/data/_class8_compute.py
Main changes:
* `get_diagnostic_data(data='alpha_pixel')` implemented
Issues:
----------
Fixed, in deve, issue #832
=> [#832] get_diagnostic_data(data='alpha_pixel') implemented

MANIFEST.in, setup.py
Main changes:
* The `Ge` atomic scattering factors input file is now included in `MANIFEST.in` and `setup.py`
=> Added spectro data missing

tofu/spectro/_fit12d_dextract.py
Main changes:
* The constraints on `amp`, `width` and `shift` were not properly propagated to `dextract['d3']`, but only to `sol_detail` and `sol_tot`.
* It explains why I did not see the problem earlier, because the plotting routines only use `sol_detail` and `sol_tot`, which were correct 
* Fixed
Issues:
-----------
Fixes, in devel issue #827
=> Fixed constrains in dextract

tofu/data/_spectralunits.py
Main changes:
* `tofu.data.convert_spectral()` is considerably simplified, making full use of `astropy.units`
Issues:
--------
Fixes, in devel, issue #855
=> Issue855 spectral astropy units

tofu/data/_class8_vos.py, tofu/data/_class8_vos_broadband.py
Main changes:
* `compute_diagnostic_vos()` now also computes a horizontal-projection VOS 
* Uses a more straightforward method based on 2d binning
Issues:
--------
Fixes, in devel, issue #859
=> Issue859 phor from vos

tofu/data/_class8_los_data.py, tofu/geom/_comp_solidangles.py
Main changes:
* `compute_diagnostic_solid_angle(return_vector=True)` implemented and debugged
Issues:
--------
Fixes, in devel, issue #861
=> Issue861 solid angle

tofu/data/_class8_compute_signal.py, tofu/tests/tests09_tutorials/tuto_real0.py
Main changes:
* `compute_diagnostic_signal(method='vos')` implemented for broadband
Issues:
----------
Fixes, in devel, issue #863
=> VOS signal for broadband

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_plot_vos.py, tofu/data/_class8_vos.py, tofu/data/_class8_vos_broadband.py
Main changes:
* `compute_diagnostic_vos(return_vector=bool)` implemented
* `compute_diagnostic_vos(keep3d=bool)` implemented
This should be taken as a first step towards a unification of vos for broadband abd spectro diagnostics, as one is merely the generalization of the other.
Issues:
-------
Fixes, in devel, issue #866
=> VOS with unit vectors and full 3d pts now optinally returned / stored for broadband

tofu/data/_class8_los_data.py
Main changes:
`interpolate_along_los()` now also returns a `'ind'` dict storing flattening indices
Issues:
-------
Fixes, in devel, issue #887
=> [#887] interpolate_along_los() now also returns a flatten index array

tofu/data/_class8_compute_signal.py
Main changes:
Minor, no real change, just clarifying
=> Issue891 debug vos synth signal spectro

tofu/data/_class02_Rays.py, tofu/data/_class02_save2stp.py, tofu/data/_class8_los_angles.py
Main changes:
* `save_to_step()` implemented, tested with NX
* Works for multi-segmented LOS
* Works for 1d and 2d cameras
* Automatically removes nans
* Can also export only outline pixels
* Can use a scaling factor (e.g.: m => mm)
* Can export from a `Collection`, from a local `.csv` or `.dat` file, or directly from `(ptsx, ptsy, ptsz)` arrays
Issues:
--------
Fixes, in devel, issue #885 
Examples:
-----------
=> Issue885 save to stp

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_plot_coverage.py
Main changes:
* `plot_diagnostic_geometrical_coverage()` implemented
Issues:
-------
Fixes, in devel, issue #903 
Example:
----------
```
dax = coll.plot_diagnostic_geometrical_coverage('OMP', plot_config=conf)
```
=> [#903] plot_diagnostic_geometrical_coverage() operational

tofu/data/_class08_save2stp.py
Main changes:
*  Fixed `save_to_stp()` for optics
=> [#905] Fixed save_to_stp() for optics

tofu/spectro/_rockingcurve.py
Main changes:
--------------------------
- `plot_therm_exp` if `therm_exp` is True, 
- plot both pola in RCs with `both_pola` arg, 
- debug `plot_asf` vs sin(theta)/lambda, 
- fs arg for all plot routines, 
- `plot_asymmmetry` if `miscut `is True
Issues:
Fixes, in devel, issue #908
=> Issue908 comput rockingcurve issues

tofu/data/_class2_check.py, tofu/data/_class8_los_data.py
Main changes:
* `interpolate_along_los(key_diag=str)` now accepts a `rays` key
* `interpolate_along_los()` has better error msg in case of ray with no valid point in the desired range (`radius_max`)
Issues:
-------
Fixes, in devel, issue #915
=> Better interpolate_along_LOS()

tofu/data/_class8_los_data.py
Main changes:
Minor bug fixed
Issues:
--------
Finalizes issue #915
=> interpolate_along_los() : Fixed minor bug

tofu/spectro/_spectralrange2d.py
Main changes:
* `spectral_range_2d()` now returns the dict of axes + larger figure
* `spectral_range_2d(varrad_b)` allows to handle variable radii sinusoidal spiral crystals
Issues:
-------
Fixes, in devel,:
* issue #919 
* issue #922
=> Better spectral_range_2d()

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_plot_coverage.py
Main changes:
* `plot_diagnostic_geometrical_coverage()` now :
- sets `key` automatically if there is single `diagnostic` available
- accepts `cmap`, `vmin` and `vmax` from the user
- accepts `nan0` to be set by the user (defaults to `True`)
Issues:
--------
Fixes, in devel, issue #923
=> Better `plot_diagnostic_geometrical_coverage()`

tofu/data/_class8_compute_signal.py, tofu/data/_class8_plot_vos.py, tofu/data/_class8_vos.py, tofu/data/_class9_compute.py
Main changes:
* `get_dvos_xyz()` has more informative error msg
Issues:
--------
Fixes, in devel, issue #925
=> [#925] Better error msg and key_diag now updated

.github/workflows/test-complete-matrix.yml, tofu/data/_class8_reverse_ray_tracing.py
Main changes:
* debugged in case `lamb = None` and `res_lamb = None`
Issues:
---------
Fixes, in devel, issue #927
=> Minor debug of reverse ray-tracing

tofu/data/_class08_Diagnostic.py, tofu/data/_class08_get_data.py, tofu/data/_class8_plot.py
Main changes:
* Fixed minor bug in `get_diagnostic_data()` (`dav` is a dict of lists)
* Fixed missing kwdarg `keyZ` from `plot_diagnostic_data()`
Issues:
--------
Fixes, in devel, issues:
* #937
* #939
=> Issue937 get data bug

requirements.txt, setup.py, tofu/data/_class10_checks.py, tofu/data/_class10_compute.py, tofu/data/_class8_check.py, tofu/tests/tests07_inversions/test_01_isotropic.py
Main changes:
* inversions with constraints are better handled
* unit tests now test inversions with constraints
Issues:
---------
Fixes, in devel, issue #948
=> Debugging using tutorial notebook

requirements.txt, setup.py, tofu/data/_class00_Config.py, tofu/data/_saveload.py
Main changes:
------------------
`spectrally` now replaces `bsplines2d` as the main dependency
Issues:
-------
Fixes, in devel, issue #954
=> spectrally has the main dependency

.github/workflows/test-complete-matrix.yml, tofu/geom/_core.py
Main changes:
Partially fixes the workflow (but not really the problem), by removing `windows` with `python 3.10` from test (temporary)
Issues:
-------
Partially fIxes, in devel, issue #960  (see for details)
But more sound solutions should come from [Cython 6384](https://github.com/cython/cython/issues/6384)
=> long vs long long => remove tests on `windows + python 3.10`

tofu/data/_class8_plot.py
Main changes:
Fixed by removing the premature `return`, which was outdated
Issues:
-------
Fixes, in devel, issue #978
=> [#978] fixed by removing return

tofu/data/_class8_plot.py
Main changes:
Second fix
Issues:
-------
Fixes, in devel, issue #978
=> [#978] Fixed

tofu/data/_class08_Diagnostic.py, tofu/data/_class08_loadfromjson.py, tofu/data/_class08_save2json.py, tofu/data/_class08_saveload_from_file.py
Main changes:
* `save_diagnostic_to_file()` now more robust vs missing `los` and `vos`
* `load_diagnostic_from_file()` now more robust vs missing `los` and `vos`
Issues:
-------
Fixes, in devel, issue #981
=> `save_diagnostic_to_file()` and `load_diagnostic_from_file()` more robust vs missing `los` and `vos`

tofu/data/_class02_save2stp.py, tofu/data/_class2_check.py
Main changes:
* `_class2_check.py` more robust vs:
- `add_rays()` with only start and pts
- better error msg
Issues:
-------
Fixes, in devel, issue #990
=> [#990] Fixed

tofu/imas2tofu/_comp.py, tofu/imas2tofu/_core.py
Main changes:
* `imas2tofu` is more robust vs dtype
Issues:
--------
Fixes, in devel, issue #1009
Examples:
------------
Now works on Tullio's env
One can plot for example the poloidal minor radius
=> [#1009] imas2tofu mMore robust vs dtype

tofu/data/_class01_Plasma2D.py, tofu/data/_class01_eqdsk.py, tofu/data/_utils_types.py, tofu/geom/_comp_solidangles.py
Main changes:
* `load_equilibrium_from_eqdsk()`:
- now automiatically groups `EQDSK` files by compatible shape groups
- allows sorting files by any vector
- Loads more predefined quantities
- Handles units better
* `tofu/data/_utils_types.py` introduced to hold all useful data types
Issues:
-------
Fixes, in devel, issue #1014
=> Better eqdsk loading

tofu/data/_class02_sample.py, tofu/data/_class8_compute_signal.py
Main changes:
* `interpolate_along_los()` fixed (axis error)
Issues:
--------
Fixes, in devel, issue #1019
=> `interpolate_along_los()` fixed

tofu/imas2tofu/_comp_toobjects.py, tofu/imas2tofu/_core.py
Main changes:
* `MultiIDSLoader.to_Plasma2D(coll=...)` implemented (optional)
Issues:
--------
Fixes, in devel, issue #1020
=> [#1020] `to_Plasma2D(coll=...)` implemented

requirements.txt, setup.py, tofu/data/_saveload.py
Main changes:
* `load(coll=...)` implemented
Issues:
---------
Fixes, in devel, issue #1029
=> Issue1029 load coll

requirements.txt, setup.py, tofu/data/_class08_Diagnostic.py, tofu/data/_class08_generate_rays.py
Main changes:
* `add_rays_from_diagnostic(strict=bool)` implemented
Issues:
--------
Foxes, in devel, issue #1038
=> [#1038] `add_rays_from_diagnostic(strict=bool)` implemented

tofu/imas2tofu/_comp_toobjects.py
Main changes:
* `to_Plasma2D()` now handles cases where both rectangular and triangular meshes are defined in ids
* Better error msg when looking for 1d radial mesh
Issues:
-------
Fixes, in devel, issue #1031 
Known issue:
With `user='imas_simulation'` the ids 'equilibrium' has non-constant 1d radial mesh, not handled by tofu
=> Issue1031 double grid

tofu/data/__init__.py, tofu/data/_core.py
Main changes:
* Remove dynamic assignment of signatures in deprecated `tofu/data/_core.py`
=> [#1040] dynamic assignment of signatures in deprecated `tofu/data/_core.py`

tofu/__init__.py, tofu/omas2tofu/__init__.py, tofu/omas2tofu/_ddef.py, tofu/omas2tofu/_equilibrium.py, tofu/omas2tofu/_main.py, tofu/omas2tofu/_utils.py
Main changes:
* `tf.omas2tofu.load_from_omas(pfe, prefix=str, strict=bool)` implemented  
Issues:
-------
Fixes, in devel, issue #1046
Known issues:
Only handles summary and equilibrium so far, need clarification on poloidal vs toroidal flux coordinates equilibrium vs core_profiles.
Examples:
-----------
`
coll = tf.omas2tofu.load_from_omas('/data/home/dvezinet/storage-root/71041_OMAS_IDS.json', prefix='71041', strict=False)
`
=> Issue1046 omas2tofu

tofu/data/_class8_los_angles.py
Main changes:
* `vos` computed in a more robust way from `los`, using more points, with a strict minimum of 2 points
Issues:
-------
Fixes, in devel, issue #1052
=> [#1052] Finer resolutions and minimum 2 points

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_plane_perp_to_los.py, tofu/data/_class8_plot.py, tofu/data/_class8_plot_vos.py
Main changes:
* `plot_diagnostic(plot_pcross=bool, plot_phor=bool)` implemented
* `plot_diagnostic_vos(plot_pcross=bool, plot_phor=bool)` implemented
* `compute_diagnostic_solidangle_from_plane()` now also plots all channels
Issues:
-------
Fixes, in devel, issue #1057
Examples:
-----------
=> [#1056] `plot_diagnostic_vos(plot_pcross=bool, plot_phor=bool)` implemented & better `compute_diagnostic_solidangle_from_plane()`

tofu/physics_tools/__init__.py, tofu/physics_tools/geometry/__init__.py, tofu/physics_tools/geometry/_pinhole_camera_estimator.py
Main changes:
* `tf.physics_tools.geometry.pinhole_camera_estimator()` implemented
Issues:
--------
Fixes, in devel, issue #1059 
Examples:
-----------
```
dout = tf.physics_tools.geometry.pinhole_camera_estimator()
```
```
dout = tf.physics_tools.geometry.pinhole_camera_estimator(ap_size=1.7e-2)
```
=> [#1059] `geometry.pinhole_camera_estimator()` implemented

.github/workflows/test-complete-matrix.yml, requirements.txt, setup.py, tofu/data/_class02_Rays.py, tofu/data/_class02_single_point_camera.py, tofu/tests/tests08_diagnostics/test_01_diagnostics.py
Main changes:
* `add_single_point_camera2d()` now takes also pre-existing data for angles and / or ref, and aloows to choose units
* corresponding unit test implemented
* Updated dependencies to `datastock >= 0.0.52`
Issues:
--------
Fixes, in devel issue #1067
=> Issue1067 single point existing data

tofu/data/_class08_Diagnostic.py, tofu/data/_class2_sinogram.py, tofu/omas2tofu/_common.py, tofu/omas2tofu/_ddef.py, tofu/omas2tofu/_equilibrium.py, tofu/omas2tofu/_main.py, tofu/omas2tofu/_utils.py
Main changes:
* `load_from_omas(ids=str/list)` implemented
* Now also handles `pulse_schedule`
* In `equilibrium` now also handles separatrix and X-points
=> Issue1071 omas boundary

requirements.txt, setup.py, tofu/version.py
Main changes:
Added `physics_tools/transmission/inputs_filter/__init__.py` so it's included in the packaging
=> Prepare 1.8.11

MANIFEST.in, pyproject.toml, tofu/version.py
Main changes:
----------------------
* Added license in `pyproject.toml`
=> Prepare 1.8.14

MANIFEST.in, setup.py, tofu/version.py
Main changes:
---------------------
Edited MANIFEST.in
Removed License from Classifiers
=> Prepare 1.8.15

tofu/omas2tofu/_common.py
Main changes:
Doesn't crash if can't find subkey
Issues:
--------
Fixes, in devel, issue #1094
=> [#1094] Done

tofu/data/_class02_save2stp.py, tofu/data/_class08_Diagnostic.py, tofu/data/_class8_plot_coverage.py
Main changes:
* `plot_diagnostic_geometrical_coverage(key_cam=str/list)` implemented
* Also by default plots all cameras that have `vos` and ignore those that don't
* `save_rays_to_stp(chain=int / tuple(int))` implemented to mimic `chain='pixel'` for pure rays (no camera defined)
Issues:
-------
Fixes, in devel, issues:
* #1096 
* #1098
=> [#1096] `plot_diagnostic_geometrical_coverage(key_cam=str/list)` and `save_rays_to_stp(chain=int / tuple(int))`

tofu/data/_class02_Rays.py, tofu/data/_class02_save2stp.py, tofu/data/_class03_Aperture.py, tofu/data/_class03_save2stp.py
Main changes:
* `save_optics_to_stp(keys=list of keys)` implemented
Issues:
--------
Fixes, in devel, issue #1099
=> [#1099] operational

tofu/data/_class8_vos_utilities.py
Main changes:
* `_get_overall_polygons()` more robust (typo fixed)
Issues:
--------
Fixes, in devel, issue #1116
=> [#1116] Bug fix on overall polygon computation for VOS 
