tofu/imas2tofu/__init__.py
Made two changes:
- libraries that need imas2tofu are only imported if the imas module is found
- instead of raising an error, we just raise a Warning
Fixes #62
=> Issue62 nosetest fail

tofu/geom/_GG02.pyx, tofu/geom/_GG03.pyx, tofu/geom/_core.py
Took out useless loop when using hybrid  algorithm in the `calc_signal` function 
In `geom/_core.py` fixed in-/output treatment of the signal.
None of the fails of unit tests are regarding the `calc_signal` function.
Rename all variables `num_los` to `nlos` to be more homogeneous throughout the code.
=> Issue108 calc los signal

setup.cfg, setup.py
Nose configuration
---------------------
Now by default ``python setup.py nosetests`` with run with: verbose, detailed erorrs, coverage (nose) and other utilities for debugging. But most importantly **only tests in ``tofu/tofu/tests/`` will be run**.
=> [nose-config] now nosetests will run certain paramaters as default

setup.cfg
* no longer printing matplotlib debug logs
* updated to latest version of nosetest to have the ids of the tests (retrocompatible)
* took out debugger (probably not compatible with travis)
=> [nosetests] twitching nosetest config file

tofu/geom/_vignetting_tools.pyx
Due to a bug in ``Cython``, ``ToFu`` requires now a version >= 0.26. Now the CEA servers are up to date so we can use resolve Issue #122 and set the pointer in the parallel loop as first intended.
Fixes #122
=> [Issue122]

tofu/geom/_sampling_tools.pyx, tofu/tests/tests01_geom/tests03_core.py
For  ``dmethod='rel'`` with ``method='sum``, there was a bug due to a wrong indentation.
Fixed and added a unit test to make sure this issue will not be found again
=> [bug-fix] in get_sample 

tofu/geom/_GG02.pyx, tofu/geom/_GG03.pyx, tofu/geom/_sampling_tools.pxd, tofu/geom/_sampling_tools.pyx
Optimization in ``calc_signal`` with option ``minimize=calls`` and ``method=sum``:
Now parallelization over lines of sight
=> [geom-perf] Optimization in calc_signal

tofu/geom/_comp.py, tofu/geom/_core.py
**PARTIALLY** Fixes #30 
In order to solve Issue #30, I applied [black](https://github.com/psf/black) to the file: ``tofu/geom/_comp.py``
Since this is a time consuming process, I rather check if the first first file fits the rest of the team's expectation (notably @Didou09). If so next PR will be with all ``*.py`` files, changed analogically.
=> [black] formatted comp file

tofu/geom/_comp.py, tofu/geom/_core.py
Fixes #180 
While solving PEP8 rules realized there were some useless variables called in `Ves_get_sampleS`.
Took them out both in function and call of function
=> [Issue180] took out useless params of Ves_get_sampleS

setup.py
Fixes #183 
- Now we don't specify the `gcc` compiler for Mac OSX (or any OS). It will use the system's default compiler. This fixes the above mentioned Issue as well as prevent the need for a patch (on ITER servers)
- Passed **black** on the ``setup.py`` file.
=> update in setup.py

tofu/data/_core.py, tofu/geom/_GG02.pyx, tofu/geom/_GG03.pyx, tofu/geom/_core.py, tofu/tests/tests01_geom/tests01_GG.py, tofu/tests/tests02_data/tests03_core.py
It's working now on my computer (I'll merge this to your fork first if you want @flothesof)
For the orginial PR #197
=> [bugfix/portability] handling long types on windows

tofu/geom/_core.py, tofu/version.py
Three functions added to tf.geom.Rays:
-------------------------------------------
* calc_length_in_isoflux() : compute the length inside a set of isoflux surfaces of each LOS
* calc_min_geom_radius(): compute the minimal geometrical radius (impact parameter) of each LOS
* calc_min_rho_from_Plasma2D(): compute the minimum normalized radius (or any field with a minimum on the axis) for each LOS
Fixes, in devel, issue #211
=> [Issue211] Added calc_LOS_length_in_isoflux()

setup.py
Cython’s build_ext module runs cythonize as part of the build process:
https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules
=> Setup.py should not cythonize extensions except when building. #221

doc/source/conf.py, doc/source/contributing.rst, doc/source/index.rst, doc/source/installation.rst, examples/tutorials/plot_basic_tutorial.py
What I've done, following #200:
- convert HTML install instructions to .rst (easier to maintain)
- updated install instructions to be "cleaner" (let me know what you think)
- move contributor guide to separate .rst file (cleaner)
- reworked navbar
=> [DOC] move installation instructions to .rst 

tofu/imas2tofu/_core.py, tofu/utils.py, tofu/version.py
Erratum
---------
The bug in `Rays._complete_dX12()` (see Issue #241) was not a bug: it was the input that was inappropriate (the line of sight geometry was not available in IDS). 
=> No change to Rays class
More informative camera construction from IDS
-----------------------------------------------------
A warning has been added to camera construction from ids if some channels have nan in D or u
General Improvement
I noticed that the overloading of the parent class ToFuObjectBase.__repr__() method, though very useful when everything works fine, was a problem when in debug mode inside a class because the debugger wants to print the current variables, including **_self_**. But while debugging inside the class, **_self_** is not fully valid yet and the get_summary() medthod …
=> Bug was not there, but __repr__() now more robust in debug

tofu/geom/_core.py
The variable `I` was renamed to `current` for obvious reasons in PR #236
=> [quick-bf] I variable name was left un-refactored

examples/tutorials/tuto_plot_custom_emissivity.py, tofu/geom/_GG.pyx, tofu/geom/_core.py, tofu/tests/tests09_tutorials/tests01_runall.py
=> [bug fix #255] found bug

_updateversion.py, tofu/__init__.py, tofu/geom/_comp.py, tofu/tests/tests01_geom/tests01_GG.py, tofu/utils.py
Took out all lingering `if sys.version[0]=='2':`
=> [py3] took out all tests of python version

tofu/geom/utils.py, tofu/version.py
tofu.geom.utils.create_config() now has:
* unique reference explicit config names (e.g.: 'WEST-V1', ''ITER-V2...)
* shortcuts that also refer to these reference config names ('B2', 'ITER'...)
=> More practical and also retro-compatible
Fixes, in devel, Issue #264
=> Issue264 config names

doc/source/installation.rst
In the documentation, in the installation section:
- added a warning: a ggc version of at least 8 should be used when compiling tofu for OpenMP reductions. See #183
=> [doc] added warning for mac and gcc compiler

tofu/__init__.py
When an optional package is not found, the warning message used to include the word "error" which I think lead the users to confusion.
(pep8 tweaks)
=> [enhancement] took out the word error from warning

doc/source/dev_tutos.rst, doc/source/index.rst, doc/source/release_notes/release_notes_142.rst, doc/source/releases.rst, doc/source/tofu.data.rst, doc/source/tofu.dumpro.rst, doc/source/tofu.dust.rst, doc/source/tofu.geom.rst, doc/source/tofu.rst, release_notes/release_notes_142.rst, tofu/version.py
Added:
- a how to for developers:
- tutorial on how to do a release
- tutorial on how to build the documentation / website
- the release notes to the website
=> Update in online documentation

README.md, tofu/version.py
* Added gitter badge 
* Redirected most anaconda badges to tofu's homepage on anaconda (instead of badges page)
* Redirected license badge to actual license text on GitHub
=> [Issue277] Fixed badges and added gitter badge

tofu/data/_comp.py, tofu/version.py
Main changes:
Fixed interpolation bug, original quantity was called with wrong time index, fixed in all versions of interpolating function
Minimal working example (requires imas2tofu):
----------------------------------------------------
...: shot = 54719
...: multi = tf.imas2tofu.MultiIDSLoader(shot=shot, \
...:           ids=['wall', 'pulse_schedule', 'soft_x_rays', 'equilibrium'])
...: sxr_data = multi.to_Data('soft_x_rays', plot=False)
...: sxr_cam = sxr_data.lCam[0]
...: sxr_cam.set_dsino([2.4, 0])
...: sxr_pts = sxr_cam.dsino['pts']
...: sxr_plasma = multi.to_Plasma2D()
...: rhopn_all = sxr_plasma.interp_pts2profile(sxr_pts, quant='equilibrium.2drhopn')
...: rhopn = sxr_plasma.interp_pts2profile(sxr_pts, quant='equilibrium.2drhopn', …
=> [Issue215] fixed

doc/source/release_notes/release_notes_142.rst, release_notes/release_notes_142.rst
Updated relese_notes into html documentation and switched simple back quotes to double for right text modification on online documentation
=> [doc] updated format for text modificators in release_notes

.travis.yml
Changes in travis.yml:
- took out wheel deployment since it's failing on travis
- skipping uploading deployment if the package was already uploaded (by another build)
=> [quick fix] took out wheel deployment and add skip if already in pypi

.gitignore, examples/tutorials/tuto_plot_basic.py, examples/tutorials/tuto_plot_gallery_fusion_machines.py
I created a very short tutorial covering loading ITER, WEST and JET configs, as discussed today.
=> New tutorial on builtin configs

tofu/tests/tests09_tutorials/tests01_runall.py
=> Fix issue295

_updateversion.py, setup.py, tofu/version.py
Hotfix by defining updateversion in setup.py and keeping _updateversion.py also
Fixes, in devel, Issue #292
=> [Issue292] Hotfix: both solutions

tofu/geom/_core.py, tofu/version.py
Fixes, in devel, Issue #304 
get_summary() is now properly defined for Struct and CamLOS2D, and completed with angles for both CamLOS1D and CamLOS2D
=> [Issue304] get_summary() added to Struct and CamLOS2D

setup.py
the path to the file version had twice the directory "tofu" appended:
Once here (**in** the function)
https://github.com/ToFuProject/tofu/blob/c25c76c95682f4cf57c71cf72ff987c9b37cc224/setup.py#L154
A second time here (at **call** time):
https://github.com/ToFuProject/tofu/blob/0bfdf2b272210945353004dadf3b6ee0b69ad6eb/setup.py#L189
so it was working for the ``version.py`` file in `$TOFU_DIR/tofu/tofu/`
=> Quick fix: wrong path in update version

tofu/imas2tofu/_core.py, tofu/version.py
Motivations:
--------------
* For non-experienced users, the imas interface class MultiIDSLoader shall provide an easy way to:
- load diagnostics geometries
- load experimental diagnostic data
- load all ids necessary to compute synthetic signal for a given diagnostic
* The current status allowed to do that in ~5-6 lines, provided the user knows where to get the info
* This need being a typical use-case, it should be easier / faster
Main changes:
* All diagnostocs for which a synthetic diagnostic exists are tabulated inside the class hidden attributes, along with their corresponding ids (core_profiles...)
* A method allows to instantaneously get the ids necessary for synthetic data (get_input_for_synthdiag())
* A method, add_ids_synthdiag(), calls the previous to …
=> Issue318 add synth diag ids

tofu/data/_comp.py, tofu/data/_core.py, tofu/geom/_core.py, tofu/tests/tests01_geom/tests03_core.py, tofu/tests/tests02_data/tests03_core.py
Motivations:
--------------
In the case where newcalc is False, we use a for loop over the LOS to compute the sum (integral).
I wanted to know whether there might be more efficient function available in numpy.
I asked the question on Stackoverflow.
It exists, and here it is:   np.add.reduceat()
Ref:
https://stackoverflow.com/questions/59079141/perform-numpy-sum-or-scipy-integrate-simps-on-large-splitted-array-efficient/59085492#59085492
This PR is interesting because the algorithm used when newcalc=False is very similar to the one used when (newcalc=True, method='sum', minimize='calls').
So acceleration in one case may be useful in the other.
Main changes:
* Replaced the for loop in Rays.calc_signal(newcalc=False) and Rays.calc_signal_from_Plasma2D(newcalc=False) by …
=> Faster los calc signal sum calls for newcalc=False

tofu/geom/_GG.pyx
Same as #308 but for the new algorithm implemented (activated whent `LOS_calc_signal(..., new_calc=True, ...)`).
Here are the results with the same benchmark
```
/home/ITER/mendozl/repositories/tofu/usr/lib/python3.6/site-packages/tofu-1.4.2a5-py3.6-linux-x86_64.egg/tofu/imas2tofu/__init__.py:83: UserWarning:
You do not seem to be using the latest IMAS version:
'module list' vs 'module av IMAS' suggests:
- Current version: 3.24.0-4.1.5
- Latest version : 3.25.0-4.4.0
warnings.warn(msg)
/home/ITER/mendozl/repositories/tofu/usr/lib/python3.6/site-packages/tofu-1.4.2a5-py3.6-linux-x86_64.egg/tofu/__init__.py:95: UserWarning:
The following subpackages are not available:
- tofu.mag
=> see tofu.dsub[<subpackage>] for details.
warnings.warn(msg)
In [2]: multi = …
```
=> Faster LOS calc signal with new_calc = True

tofu/geom/_GG.pyx
Issue #314 was coming from a modulo operation with `@cython.cdivision(True)`, it gives the wrong result with negative values and cdef defined variables.
Since this flags accelerates the code overall, and that the modulo operand was only being use for a -/+1 operation on a integer in [0,npts[ that should stay in [0,npts[, I decided to add one if test that should not slow down the function.
=> [ #314 ] fixed bug on mac coming from modulo with negative values

tofu/geom/_GG.pyx, tofu/geom/_basic_geom_tools.pxd, tofu/geom/_basic_geom_tools.pyx, tofu/geom/_comp.py, tofu/geom/_core.py, tofu/version.py
As discussed in #331 : 
The polygon needs to be properly defined in order for the algorithm `isClockwise` works correctly.
If it finds an issue (null volume) it will raise an exception.
The exception is caught and raised whenever function used
**Warning**: I didn't manage to properly catch and raise the error.  Can you see what I am doing wrong ? I left a `print` for the moment
I also realized in _core, `isClockwise` is defined sometimes **before** checking if the polygon is closed, however the algorithm needs for the polygon to be closed.
Lastly: some flake8 changes
=> [bf #331] raising exceptions when poly ill defined

tofu/geom/_GG.pyx, tofu/geom/_comp.py, tofu/tests/tests01_geom/tests01_GG.py
Replaced `Poly_Order` by `format_poly`:
- the function now doesn't change the layout of the polygon: a polygon should always be in the format `(cc,N) = (number_of_coordinates, number_of_points)`
- the tests were adapted
- calls were updated
Solves #337
=> [Issue #337] replaced Poly_Order by format_poly

tofu/imas2tofu/_core.py, tofu/version.py
Main changes:
* The input keyword argument 'description_2d', used to choosed the wall geometry from an imas wall IDS, is now available from all methods of MultiIDSLoader that call to_Config() in the background. These include in particular to_Plasma2D(), to_Cam(), to_Data() and calc_signal()
* When not set (description_2d=None), the variable is now automatocally set to 1 if possible (to 0 otherwise)
Example (on IRFM Intra only):
---------------------------------
```
/Home/DV226270/ToFu_All/tofu_git/tofu/tofu/imas2tofu/__init__.py:83: UserWarning: 
You do not seem to be using the latest IMAS version:
'module list' vs 'module av IMAS' suggests:
- Current version: 3.23.1-4.0.3
- Latest version : 3.25.0-4.4.0
warnings.warn(msg) …
```
=> [Issue335] description_2d propagated and set to 1 by default

.travis.yml, anaconda_upload.sh, pyproject.toml, setup.py, tofu/version.py
This PR should fix a couple of issues:
- Issue #340 :  _The version number in tofu/version.py had to be forced by hand_
The problem came from the fact that travis checkouts the tag commit of tofu so the repository is not a specific branch but on a detached HEAD. I changed the `setup.py` so that it checks if it is building a travis tag version (by checking if `$TRAVIS_TAG` exists)
https://github.com/ToFuProject/tofu/blob/d16595dbca1bc8b516f03abced987c3c2fa2f460/setup.py#L168-L169
- Issue #340 : _Apparently the deployment was also done on test-pypi_
As I mentioned in the issue, the condition `on: tags: True` sets TRAVIS_BRANCH to the tag number, thus it is no longer `master` nor `deploy-test` (nor any other branch name).
Solved this by checking to which git branch the commit hash …
=> Deploy test

tofu/utils.py, tofu/version.py
Motivation:
-------------
Safety and backward compatibility for old saved files, see:
https://stackoverflow.com/questions/41696360/numpy-consequences-of-using-np-save-with-allow-pickle-false
Main Changes:
* parameter allow_pickle, fed to np.load(), is now available to the user using tf.load()
Issues:
-------
Fixes, in devel, issue #357
=> Issue #357 Made allow_pickle available to user

tofu/scripts/_def.py, tofu/scripts/tofucalc.py, tofu/scripts/tofucustom.py, tofu/scripts/tofuplot.py, tofu/version.py
Main changes:
* User-customizable default parameters of tofuplot and tofucalc have been moved to a dedicated module tofu/scripts/_def.py
* tofu-custom now copies this module into the local .tofu/ directory so the user can edit these parameters
Issues:
---------
Fixes, in devel, issue #359
=> Issue #359 tofu-custom allow customization of script parameters

.travis.yml, release_notes/release_notes_143.rst, tofu/imas2tofu/_core.py, tofu/scripts/tofucalc.py, tofu/scripts/tofuplot.py, tofu/version.py
Realized :
os.chdir(...)
import <module>
was not robust enough, the system can chdir in a separate terminal and the import ay not see the proper module
Replaced by a more robust 
1/ temporary modification of the sys.path
2/ use of importlib library
Option 2 seems safer after some reading.
Also @lasofivec , I pushed changes to ne-doc for the bash commands, but could not build the doc because I can't install a Sphinx dependency here, could you build and push to gh-pages ?
Also: added draft for release notes for 1.4.3
=> Issue #359 Minor bug fix

release_notes/release_notes_144.rst, tofu/data/_plot.py, tofu/imas2tofu/_core.py, tofu/imas2tofu/_def.py, tofu/scripts/tofucalc.py, tofu/scripts/tofuplot.py, tofu/utils.py, tofu/version.py
Motivations:
--------------
* IMAS users may want to calculate synthetic signal using:
- diagnostic geometry from an idd (tokamak / user / shot / run)
- equilibrium from a different idd
- 1d profiles from a third idd, or from a .mat file
* Also, the data visualization was not very robust when mutiple ids were called, it would fail if a single ids would fail loading
Main changes:
* Keeping in mind the correspondence betweeb short and long versions of the arguments:
-tok = --tokamak
- u = --user
- s = --shot
- r = --run
- i = --ids
* Minor change: short version of --tokamak changed from -t to -tok
* Users of tofucalc can now provide:
- (-tok, -u, -s, -r) for the geometry
- (-tok_eq, -u_eq, -s_eq, -r_eq) for the equilibrium
- (-tok_prof, -u_prof, -s_prof, -r_prof) for the …
=> Issue #373 tofucalc multiple idd

doc/source/conf.py
Hi all,
here are some short improvements to the docs:
- fix the version number (right now Tofu 1.4 --> should be 1.4.3)
- fix the copyright notice (© Copyright 2016-2019, Tofu contributors. --> 2016 till current year)
- make use of the HTML last updated thing so that users can see when the HTML page has last been updated.
What do you think?
Regards,
Florian
=> long version name in doc title, fix copyright date future proof

.travis.yml, setup.py, tofu/scripts/tofuplot.py, tofu/scripts/tofuversion.py, tofu/version.py
Main changes:
* New script introduced `tofu-version`, to be installed upon `pip install` and called from the terminal
* Prints the version of the currently installed tofu
* optionally stores this version in an environment variable, but for some reason, while the environment variable is properly set in the scope of the module, it is not properly exported to the system 
Example:
----------
```
> tofu-version
1.4.4
```
The user can decide to store it in an environment variable:
* option 1: 
`export TOFU_VERSION=$(tofu-version)`
* option 2:
`tofu-version -envvar TOFU_VERSION`
Option 2 should be safer, since before assigning it checks whether the environment variable already exists and warns the user if it does. User must use `--force True` to overwritte.
However, for a yet …
=> Issue #385 tofu version bash

.travis.yml, scripts/_dparser.py, scripts/tofu_bash.py, scripts/tofucustom.py, scripts/tofuversion.py, setup.py, tofu/entrypoints/tofucalc.py, tofu/entrypoints/tofuplot.py, tofu/version.py
Motivation:
-------------
* Since the last release, tofu offers several bash commands:
- `tofu-version`:     to get the current version number
- `tofu-custom`:     to create a local hidden .tofu repo for user-spefific default values
- `tofuplot`:            to load and plot diagnostic data from imas
- `tofucalc`:            to load profiles, diag geometry and equilibrium from imas, calculate synthetic diag data and plot it
* In order to make it easier for users and to mimic standard conventions, it makes sense to implement a single tofu command, and the arguments will determine which of the sub-commands above is called:
- `tofu --version`     for tofu-version
- `tofu custom`        for tofu-custom
- `tofu plot` ....         for tofuplot ...
- `tofu calc`...           for tofucalc ... …
=> Issue #403 : Single tofu bash command

tofu/imas2tofu/_core.py, tofu/utils.py, tofu/version.py
The bck kwdarg lets the user decide whether he/she wants all time steps / profiles to be displayed as a grey background on interactive plots.
This background is useful for working, but is not very pretty for publication figures, hence the introduction of bck to let the user choose whether to have the background or not.
tofucalc was not correctly using the kwdarg bck.
It was due to the fact bck had been correctly propagated to functions called by tofucalc
Example (IRFM intra only):
-----------------------------
With background (default)
```
./tofu/entrypoints/tofucalc.py -s 55323 -i bolometer -u_eq CB165101 -r_eq 1 -u_prof CB165101 -r_prof 1 &
```
Without background:
```
./tofu/entrypoints/tofucalc.py -s 55323 -i bolometer -u_eq CB165101 -r_eq 1 -u_prof CB165101 -r_prof 1 -bck False &
``` …
=> Issue #401: tofucalc bck kwdarg propagation

tofu/data/_plot.py, tofu/entrypoints/_def.py, tofu/version.py
Motivations:
--------------
* standard tofu bash commands were not woking anymore since the last release
Main changes:
* The issue was that default config for tofuplot was set to False => reset to None
Example (on intra only):
--------------------------
```
[~/] ./tofu/entrypoints/tofuplot.py -i ece interferometer -s 55178
Getting ids     [occ]  tokamak  user         version  shot   run  refshot  refrun
--------------  -----  -------  -----------  -------  -----  ---  -------  ------
ece             [0]    west     imas_public  3        55178  0    -1       -1    
equilibrium     [0]    "        "            "        "      "    "        "     
ic_antennas     [0]    "        "            "        "      "    "        "     
interferometer  [0]    "        "            " …
```
=> Issue422 tools dc5

tofu/data/_core.py, tofu/imas2tofu/_comp.py, tofu/imas2tofu/_comp_toobjects.py, tofu/imas2tofu/_core.py, tofu/imas2tofu/_def.py
Motivation:
--------------
*exporting to a Plasma2D instance from a MultiIDSLoader should work on ITER, even with quasi-empty equilibrium and only one time slice
Main changes:
* Multi.to_Plasma2D() is now more robust, the user can pick the desired ids, the error messages are more detailed, and the user can exclude any dextra
* The Multi.get_data() method is now less verbose and more compact
Working example:
------------------------
```
In[9]: multi = tf.imas2tofu.MultiIDSLoader(ids=['edge_sources', 'edge_profiles', 'equilibrium'], shot=134000, run=30, tokamak='iter', user='public')
Getting ids     [occ]  tokamak  user    version  shot    run  refshot  refrun
--------------  -----  -------  ------  -------  ------  ---  -------  ------
edge_profiles   [0]    iter …
```
=> Fixing ITER-related issues

tofu/geom/_GG.pyx
It seems that this fixes the issues in #431 on my windows machine.
My explanation:
- under linux np.argmax does indeed return longs
- under windows it doesn't 
Solution:
- explicitly convert dtype
=> fix issue 431

doc/source/contributing.rst, doc/source/installation.rst
Corrected the doc to use `pytest` instead of `nosetest`
=> [doc] corrected nosetest > pytest

examples/tutorials/tuto_plot_basic.py, examples/tutorials/tuto_plot_custom_emissivity.py, examples/tutorials/tuto_plot_gallery_fusion_machines.py, tofu/geom/utils.py, tofu/version.py
Motivations:
* Geometrical qrgument names for tf.geom.utils.create-CamLOS1D() and tf.geom.utils.create-CamLOS2D() were not clear and intuitive enough
* The docstrings did not provide enough clarification
* But args cannot be changed abruptly between 2 versions, some time has to be given to users to adapt
* 
Main changes:
* New arguments have been implemented:
P      ->  pinhole
F      ->  focal
D12  -> sensor_size
N12  -> sensor_nb
angs -> orientation
* But old arguments are still operation, for retro-compatibility
* A DeprecationWarning is raised everytime a user passes an old argument, warning him to use a new one instead and that the old ones will not be supported in the future
* The docstr now include 2 fully operational example that can be …
=> Issue #473 explicit arguments for create cam

tofu/data/_core.py, tofu/geom/_core.py, tofu/geom/_def.py, tofu/pathfile.py, tofu/tests/tests01_geom/test_01_GG.py, tofu/tests/tests02_data/test_03_core.py, tofu/utils.py, tofu/version.py
Motivations:
--------------
* The unit tests in [GA](https://github.com/ToFuProject/tofu/runs/2004133116?check_suite_focus=true) showed a few warnings that seemed easy to remove
Main changes:
* A few minor changes (in particular several occurences of `np.int`  or `np.long` replaced by `int` as recommended [here](https://numpy.org/devdocs/release/1.20.0-notes.html)).
Issues:
-------
* Fixes, in devel, issue #475
=> Issue #475 Remove some easy warnings

conda_recipe/meta.yaml, requirements.txt, setup.py, tofu/version.py
Motivations:
--------------
* I realised one dependency was missing: the library `requests`
* It necessary only for the subpackage `openadas2tofu`, which is rarley used and not tested yet, which explains why we did notice it before
Main changes:
* Added to `setup.py`
* Added to `requirements.txt`
* Added to the run-time section of `conda_recipe/meta.yaml`
I think that's it, except if it is also needed in `pyproject.toml`?
@lasofivec, can you double-check whether all dependencies need to be in `pyproject.toml`? 
Currently `scipy`, `matplotlib` and `requests` are not in there.
Issues:
-------
* Fixes in devel issue #480
=> Issue #480 Added requests to setup.py, requiremens.txt and conda_recipe/meta.yaml

scripts/_dparser.py, tofu/imas2tofu/_comp_toobjects.py, tofu/imas2tofu/_core.py, tofu/imas2tofu/_def.py, tofu/version.py
Motivation:
------------
* tofuplot was not able to load ids wall 
* The names of the structures stored in ids wall are non-conform (include blank spaces and underscores) and are not handled correctly by tofu
Main change:
* tofuplot can now handlle ids wall
* All names are now scanned for ' ' and '_' , which are removed and the various parts of the names are capitalized
Example (on hpc-login02):
-----------------------------
./tofu/entrypoints/tofuplot.py -i wall -tok ITER_MD -u public -r 17 -s 1180
Issues:
-------
* Issue #442 is fixed in devel
* Issue #485 is opened to address the fact that the polygons stored in IMAS are not closed and represent 2 parts of the same polygon.
=> Issue #442 read ids wall iter

tofu/openadas2tofu/_requests.py
Motivations:
* the submodule `openadas2tofu` directly sends a request online to [openadas](https://open.adas.ac.uk/) using the built-in library `requests`, read the answer (html), parse it and extract the info of interest
* It works fine at CEA and on my own laptop (and in unit tests on Travis and Github), but not on ITER clusters
Main Changes
* A [ticket](https://jira.iter.org/browse/IMAS-3698?filter=-2) was opened to ask ITER admins their feeling about it
* It lead to the creation of a second [ticket](https://jira.iter.org/servicedesk/customer/portal/1/ITSD-191846) to the IT team
* It seems the requests library used, has its own list (bundle) of certificates for ssl connections, and apparently, for some unknown reason, this bundle of certificates …
=> [#500] Openadas on ITER

tofu/geom/_comp.py, tofu/version.py
Motivations:
--------------
* `Config.from_svg()` allows the user to set the origin `r0`
* But if `r0` is too large, some structures may have negative R, which is impossible in toroidal geometry
Main changes:
* A warning is implemented so when it happens it explains that r0 is too large and displays the names of the Structures that are deleted due to this issue.
Issues:
-------
* Fixes, in devel, issue #518 
Example:
----------
Here 2 structures are deleteddue to this problem: `limiter` and `pfcoil`
```
In [1]: import tofu as tf                                                                                                                                                              
conf /Home/DV226270/ToFu_All/tofu_git/tofu/tofu/imas2tofu/__init__.py:87: UserWarning: …
```
=> [#518] Implement warning when Config.from_svg() has r0 too large

tofu/geom/_core.py, tofu/version.py
Motivations:
--------------
* see issue #522 
Main Changes:
* Closed polygons are a particular and common case, they are treated separately before raising a warning
Example:
----------
When loading from a svg no warning is raised anymore everytime a closed polygon is loaded
```
In [1]: import tofu as tf                                                                                                                                                              
/Home/DV226270/ToFu_All/tofu_git/tofu/tofu/imas2tofu/__init__.py:87: UserWarning: 
You do not seem to be using the latest IMAS version:
'module list' vs 'module av IMAS' suggests:
- Current version: 3.30.0-4.8.4
- Latest version : 3.32.1-4.9.1-R2019b
warnings.warn(msg)
In [2]: conf = …
```
=> [#522] Closed polygons treated separately => no warning

tofu/geom/_check_optics.py, tofu/geom/_core_optics.py, tofu/tests/tests01_geom/test_04_core_optics.py, tofu/version.py
Motivations:
--------------
* see issue #537 
Main changes:
* The `Crystal.split()` method is implemented
* It takes 2 kwdargs: 
- `'direction'`: specify the splitting direction (`'e1'` or `'e2'`)
- `'nb'`: specify in how many equal parts the crystal must be splitted
* It returns a list of new Crystal instances
Issues:
-------
* Fixes, in devel, issue #537 
Example:
----------
```
In [1]: import tofu as tf                                                                                                                           
/Home/DV226270/ToFu_All/tofu_git/tofu/tofu/imas2tofu/__init__.py:87: UserWarning: 
You do not seem to be using the latest IMAS version:
'module list' vs 'module av IMAS' suggests:
- Current version: 3.30.0-4.8.4
- Latest version : …
```
=> Issue537 crystal splitting

tofu/geom/_core_optics.py, tofu/geom/_plot_optics.py, tofu/tests/tests01_geom/test_04_core_optics.py
Motivation:
-------------
* see Issue #540 
Main changes:
* The user can determine a wavelength interval of validity thanks to new entry agruments into `cryst.plot_focal_error_summed()`.
* This condition is fullfilled into cryst.calc_johannerror() and the domain of validity is plotted as the same time of the method.
* Added possibility to plot ray-tracing in order to visualize non focalization.
Issues:
-------
* Fixes, in devel, Issue #540 
Example:
---------
```
In [1]: import tofu as tf                                                                                                                                                                                       
In [2]: import inputs_temp.XICS_allshots_C34 as xics …
```
=> Issue 540 - Wavelength Interval

.travis.yml
now only `master`, `devel`, `deploy-test` and tagged commits will be tested in travis.
=> [CI/CD] simplified travis

.github/workflows/python-package-pip-testing.yml, conda_recipe/meta.yaml, requirements.txt, setup.py, tofu/version.py
Motivations:
--------------
* see issue #582 
* Adding svg.path as a compulsory dependency for users results from the following reasons:
* to avoid crashing conda-forge
* because importing a tokamak geometry from inkscape is one of the popular features of tofu
* because svg.path seems available on ll platforms both from [Pypi](https://pypi.org/project/svg.path/) and [anaconda.org](https://anaconda.org/conda-forge/svg.path)
Main changes:
* Added svg.path to setup.py, requirements.txt, conda_recipe/meta.yaml
=> [#582] Added svg.path to setup.py, requirements.txt, meta.yaml

.github/workflows/complete-matrix.yml, tofu/version.py
Motivations:
--------------
* Python 3.10 was recently released
* We cannot test everything, but a number of 3 python versions seems reasonable
* Up to now we were testing 3.6, 3.7 and 3.8
* It is  bit early to test 3.10, since many libraries do not use it yet
* However it seems reasonable that we should test at least python 3.9
* see issue #567 
Main changes:
* Testing matrix no w tests against 3.7, 3.8 and 3.9
=> [#567] Removed python 3.6, added 3.9 to testing matrix

tofu/_plot.py, tofu/data/_DataCollection_plot.py, tofu/data/_plot.py, tofu/geom/_plot.py, tofu/spectro/_plot.py, tofu/utils.py, tofu/version.py
Motivations:
--------------
* see Issue #593 
* As suggested by [this post](https://stackoverflow.com/questions/20711148/ignore-matplotlib-cursor-widget-when-toolbar-widget-selected), The interactivity was lost due to the private attribute `toolbar._active` being suppressed since [this commit](https://github.com/matplotlib/matplotlib/commit/2d41a724aa711decceba1a1df3fa167c585fbdaa) in matploltib
* The private attribute was replaced by a public one `toolbar.mode` 
Main changes:
* tofu updated to use the public attribute `toolbar.mode` ony
* Used this opportunity to fix all warnings regarding `canvas.set_window_title()` (deprecated and replaced by `canvas.manager.set_window_title()`)
* Interactivity recovered
Issues:
-------
* Fixes, in devel, issue #593 
* Known issue: …
=> Figure interactivity lost

tofu/geom/_check_optics.py, tofu/geom/_comp_optics.py, tofu/geom/_core_optics.py, tofu/geom/_plot_optics.py
Motivations:
* Start implementing a synthetic diagnostic
* Useful for preparing inversions too
Main changes:
* A `CrystBragg.calc_signal_from_emissivity()` method is implemented
* It allows the user to define any arbitrary spectral emissivity function at any point in the plasma that will be used to compute the signal received on a detector
Example:
-------------
```
In [2]: binning = (172e-6*(np.arange(0, 487) - (487-1)/2), 172e-6*(np.arange(0, 1467) - (1467-1)/2))
In [3]: det = dict(np.load('inputs_temp/det37_CTVD_incC4_New.npz'))
In [4]: conf0 = tf.load_config('WEST-V0')
In [5]: cryst = tf.load('tofu/tests/tests04_spectro/test_data/TFG_CrystalBragg_ExpWEST_DgXICS_ArXVII_sh00000_Vers1.4.15-112-gddc0126a.npz')
Loaded from: …
```
=> [#600] Added Cryst.calc_signal_from_emissivity(), operational with plot

doc/source/contributing.rst, doc/source/dev_tutos.rst, doc/source/installation.rst
As discussed at the end of https://github.com/ToFuProject/tofu/issues/599#issuecomment-990032743, here is a small review and improvement of the docs regarding mostly installation.
Notable changes to doc:
- removed specialized instructions in favor of conda-forge for normal users: I believe it’s simpler to advertise this "one size fits all solution" rather than the previous version
- rewrote developer install and made sure it works on my machine
- better links to other parts of the doc
Possible improvements I saw while working on this:
- the "normal" tests took 11 minutes to complete, this is really crazy since they took less than 2 minutes a couple of months ago --> this is something that will probably deter contributors
- I don’t understand the "how to construct the doc" section …
=> update doc as of 2022

.github/workflows/complete-matrix.yml, requirements.txt, tofu/geom/_GG.pyx, tofu/geom/_sampling_tools.pyx, tofu/tests/tests01_geom/test_01_GG.py
Bugfix for #612:
The error came from the fact that a `floor` operation was done on a variable of value `4.99999....`. Usually, the compiler guesses that the number is actually `5` and thus returns `5` on the `floor` operation. Just for this particular example, it wasn't.
See the comments to see how  I fixed but basically, I added a small epsilon so that the `floor` operation returns the right value and no other results will be affected by this operation.
=> Issue #612 bf

tofu/imas2tofu/_def.py, tofu/version.py
Main changes:
* Added ids summary to tofu-known ids's from IMAs, with many key signals
Issues:
-------
* Fixes, in devel, issue #621 
Examples:
-----------
```
In [2]: multi = tf.imas2tofu.MultiIDSLoader(shot=56681, ids=['summary'], ids_base=False)
Getting ids  [occ]  database  user         version  shot   run  refshot  refrun
-----------  -----  --------  -----------  -------  -----  ---  -------  ------
summary      [0]    west      imas_public  3        56681  0    -1       -1    
In [3]: tf.imas2tofu.MultiIDSLoader.get_shortcutsc('summary')
ids      shortcut        units  long version                              
-------  --------------  -----  ------------------------------------------
summary  beta_pol        - …
```
=> [#621] Added some key signa from ids summary

tofu/spectro/_fit12d.py, tofu/spectro/_fit12d_dextract.py, tofu/version.py
Main changes:
* Saturation of amp is explored
=> turns out it was mostly due amplitudes close to 0
=> But 0 amplitude is acceptable, should not raise a warning
=> Amp are now allowed to be close to 0, solves most problems
* More informative saturation messages:
=> now prints also the average number of bsplines for wich there was saturation
=> Issue539 fit2d

tofu/spectro/_rockingcurve.py
Motivations:
-------------
* The `cryst.compute_rockingcurve()` method should work without any entry arguments. If its the case, default parameters have to be attribuated.
* In parallel, the `dout `dict should return exact values, not rounded values. Rounding should be done only at printing time, in `lstr`.
Results:
* Adding specific conditions for type of arguments:
* * Default value assignment if all entry arguments are not specified
* * If missing 1 or more, but not all, an error message is shown 
* * If entry agruments are `str` values, another error message is shown 
* exit dictionary `dout `contains now the exact values and the rounding operations are done at the printing part
Main changes:
--------
* The `CrystBragg_check_inputs_rockingcurve()` method now contains: …
=> [#626] Correcting args if all are None & Exception messages if any is None

tofu/geom/_core_optics.py, tofu/spectro/_rockingcurve.py
Motivations:
* Integer an asymmetry property called non-parallelism between crystal's optical surface and inter-atomic planes into the rocking curve computations.
* Study the effect of the well-known non-parallelism specific of Bragg crystals used in WEST on their reflecting curves. 
Results:
----------
* This option is now available through the entry argument `use_non_parallelism = True`.
* This asymmetry is designed to vary between plus and minus the Bragg angle corresponding to the chosen wavelength, within 0.01 radians.
* The argument `na` let the choice of the number of steps between the asymmetry limits. It fixed to 51 steps by default.
* The `na` values of the integrated reflectivities, ratio between parallel and perpendicular components, widths of curves and …
=> Issue629 non parallelism into rocking curves

tofu/data/_core.py, tofu/version.py
Main changes:
* Added vr1 and vr2 were missing, added
Issues:
----------
* Fixes, in devel, issue #633 
Example:
------------
```
In [2]: multi = tf.imas2tofu.MultiIDSLoader(shot=54178, ids=['equilibrium', 'core_profiles'])
Getting ids     [occ]  database  user         version  shot   run  refshot  refrun
--------------  -----  --------  -----------  -------  -----  ---  -------  ------
core_profiles   [0]    west      imas_public  3        54178  0    -1       -1    
equilibrium     [0]    "         "            "        "      "    "        "     
pulse_schedule  [0]    "         "            "        "      "    "        "     
wall            [0]    "         "            "        "      "    "        "     
In [3]: plasma = …
```
=> #633: vr1 and vr2 were missing for 1d linear interpolation for triangular meshes

tofu/imas2tofu/_core.py, tofu/imas2tofu/_def.py, tofu/utils.py, tofu/version.py
Main changes:
* imas2tofu updated to handle HDF5 backend
Example:
----------
* The two following command are equivalent since HDF5 is now the default backend
```
In [2]: multi = tf.imas2tofu.MultiIDSLoader(ids=['equilibrium', 'core_profiles'], shot=56757, backend='hdf5')
Getting ids     [occ]  database  user         version  shot   run  refshot  refrun
--------------  -----  --------  -----------  -------  -----  ---  -------  ------
core_profiles   [0]    west      imas_public  3        56757  0    -1       -1    
equilibrium     [0]    "         "            "        "      "    "        "     
pulse_schedule  [0]    "         "            "        "      "    "        "     
wall            [0]    "         "            "        "      "    " …
```
=> Issue641 imas hdf5

tofu/spectro/_rockingcurve_def.py
Main changes:
* Follow-up on PR #734 , fixing 2 minor typos:
- a `*1e10` conversion that had not been commented
- a `Silicium` => `Quartz` typo in a routine name
=> [#733] Debugged typos in _rockingcurve_def.py

pyproject.toml, requirements.txt, setup.py
Main changes:
* Re-instanciate dependency `Cython>=0.26` in `setup.py`, `requirements.txt` and `pyproject.toml`
* Re-instanciate `numpy` in `pyproject.toml` (necessary)
=> Issue731 installation missing numpy

tofu/data/_class5_projections.py, tofu/data/_class5_reflections_pts2pt.py, tofu/data/_class8_equivalent_apertures.py
Main changes:
Two minor bugs identified in the routines used to project an aperture (slit) on a concave crystal.
Concavity comes with numerical instability when the root-finding process comes close to the singular point that is the center of curvature.
Tofu implements a robust root-finding routine + interpolates reflected polygons to take out singular points.
**Bug 1:** the interpolation process was missing some corners of the polygons in some particular cases.
**Bug 2:** the root-finding algo wasn't robust enough for some particular pixels / configurations
Both bugs have been addressed in this PR, see issue #747 for examples
Several plotting / debugging sections have been added to the code to facilitate any later debugging in case another problem arises. They are …
=> Debug jumps in etendue for spectrometer concave crystals

tofu/data/_class5_reflections_pts2pt.py, tofu/data/_class8_compute.py, tofu/data/_class8_equivalent_apertures.py, tofu/data/_class8_vos_spectro.py, tofu/tests/tests09_tutorials/tuto_real0.py
Main changes:
* After fixing bugs in reflected polygon root-finding and interpolation, @cjperks7  commented that while it had fixed the `etendue`, some instabilities remained in the computation of `dlamb`, see PR #751 for details
* After investigating, it comes not from a bug but simply from an unsufficient number of interpolation points for the polygon interpolation
* The number of interpolation points has been increased, resulting in better results at the cost of slower computation
Issues:
---------
* This partially fixes issue #748, as it addresses the stability aspect of `dlamb`, but does not yet answer why `dlamb` is generally larger than expected
Examples:
--------------
This is an example of a reflection of the slit as seen through the crystal by a pixel, …
=> Correcting jumps in dlamb

tofu/data/_class8_equivalent_apertures.py, tofu/data/_class8_plot_vos.py
Main changes:
* None, except a minor extra piece of copy-pasted code to help that kind of cases debugging 
Issues:
-----------
* Issue #756  was due to wrong input, no bug detected
Example:
------------
The outline of the crystal was provided such that the crystal was self-intersecting, resulting in reflected slit that was plummeting to 0 for central pixels
Indeed, the reflection of the slit on the crystal gradually disappears as we go from edge pixels to central pixels (index ii = 16)
A simple fix is to provide the outline in good order to avoid self-intersection of the polygon:
Which results in:
=> Issue756 flat crystal etendue

tofu/data/_class8_plane_perp_to_los.py, tofu/data/_class8_reverse_ray_tracing.py, tofu/tests/tests09_tutorials/tuto_real0.py
Context:
-----------
`compute_diagnostic_solidangle_from_plane()` was taking up too much memory when used with fine resolution on a camera with several thousand pixels and fine wavelength sampling.
The main issue was the allocation of array `sang_lamb` with shape `(npix0, npix1, npts0, npts1, nlamb)`.
That array quickly got huge, leading to memory shortage and crashes.
Main changes:
---------------------
* The `sang_dlamb` array in was in fact only used to later be summed over the 3 last dimensions.
* It has been replaced by a `(npix0, npix1)` array summed over iteratively
=> Decrease memory footprint of compute_diagnostic_solidangle_from_plane()

tofu/data/_class08_Diagnostic.py, tofu/data/_class5_projections.py, tofu/data/_class8_equivalent_apertures.py, tofu/data/_class8_etendue_los.py
Main changes:
* The overestimation was only showing in cases with multiple apertures after the crystal
* In those cases, the distance used as reference for estimating the effect of the rocking curve was taken using the furthermost aperture (from the crystal)
* In fact, it should be the aperture that is the most limiting to the spectral range
As an easy fix, the new keyword arg `ind_ap_lim_spectral` is introduced to methods `compute_diagnostic_etendue_los()` and `get_diagnostic_equivalent_aperture()`.
It is set to 0 by default (because it is usually actually the closest aperture to the crystal that limits the spectral range).
But it can be set to a custom value by the user.
Issues:
-------
* fixes, in devel, issue #774
=> Issue774 overestimated etendue

tofu/spectro/__init__.py, tofu/spectro/_spectralrange2d.py
Main changes:
* `tf.spectro.spectral_range_2d()` implemented
- can plot several crystals simultaneously
- by default spans whole crystal length but can also be limited by `beta_max` (half-angular opening of beam from aperture) 
Issues:
---------
* Fixes, in devel, issue #779 
Examples:
--------------
```
In [2]: dcam = {'cent': [4.77, 0.29], 'length': 75e-6*1024*2, 'nin': [-0.2, -0.6]}
In [3]: dout = tf.spectro.spectral_range_2d(bragg0=(np.pi/180)*np.r_[24.6, 24.2, 23.8], lamb0=1.e-10*np.r_[0.944, 2.72, 1.615], xx=4.5, dist=0.6, rcurve=0.65*np.r_[np.inf, np.inf, 1], length=0.15, dcam=dcam, beta_max=np.arctan2(0.05, 12))
```
=> Issue779 crystal size2d

tofu/data/__init__.py, tofu/data/_saveload.py
Main changes:
* `tf.data.load()` implemented, calls `datastock.load()` with `Collection` class
* Uses `datastock` [PR 101](https://github.com/ToFuProject/datastock/pull/101) (available in the next release of `datastock`)
Issues:
----------
* Fixes, in devel, issue #785 
Examples:
**_Caveat_**: the following only works using the `devel` branch of `datastock` (until next release)
Using `tuto_real0.py` we easily create a Collection populated with several diagnostics:
```
os.chdir('../datastock')
import datatsock
os.chdir('../tofu')
import tofu as tf
test = tf.tests.tests09_tutorials.tuto_real0
conf, coll = test.main()
```
Frist we remove all plasma `mesh` (saving / loading not yet operational for `meshes` / `bsplines`, only for diagnostics, will be …
=> [#785] tf.load() implemented, operational for non-bsplines

tofu/data/_class5_check.py, tofu/spectro/__init__.py, tofu/spectro/_rockingcurve.py, tofu/spectro/_rockingcurve_def.py, tofu/spectro/_rockingcurve_tools.py, tofu/tests/tests09_tutorials/tuto_real0.py
Main changes:
* `tf.spectro.scope_reflected_intensities()` implemented
- basically based on the [MWE](https://github.com/ToFuProject/tofu/pull/796#issuecomment-1625663599) from PR #796 
- also allows to plot simultaneously several desired wavelengths
- `wavelength` are color-coded, `materials` are marker-coded 
* To be used as a practical one-liner to quickly get an overview of solutions for several wavelengths and materials
Issues:
-------
Fixes, in devel, issue #801 
Examples:
-----------
```
import tofu as tf
dout, ax = tf.spectro.scope_reflected_intensities(target_lamb=np.r_[0.944, 1.630, 2.72]*1e-10)
```
=> Issue801 scope integrated reflectivity

tofu/data/_class02_Rays.py, tofu/data/_class2_plot.py, tofu/data/_class2_sinogram.py, tofu/tests/tests08_diagnostics/test_01_diagnostics.py, tofu/tests/tests09_tutorials/tuto_real0.py
Main changes:
* get_sinogram() implemented, with a plotting option
- can handle a diag key, a list of rays keys and a config
- can plot
- can handle 4 different conventions (ang='theta' or  'xi', impact_pos=bool)
- angle = `'theta'` in [-pi, pi] and impact parameter positive
- angle = `'theta'` in [0, pi] and impact parameter signed
- angle = `'xi'` in [-pi, pi] and impact parameter positive
- angle = `'xi'` in [-pi/2, pi/2] and impact parameter signed
Issues:
--------
Fixes, in devel, issue #808 
Examples:
-----------
```
import tofu as tf
test = tf.tests.tests09_tutorials.tuto_real0
conf, coll = test.main()
dax = coll.plot_diagnostic('d0', elements='o', plot_config=conf)
```
Plotting all four conventions for the same set of rays:
```
dout, dax = coll.get_sinogram('d0', …
```
=> Issue808 sinograms

tofu/data/_class10_algos.py, tofu/data/_class10_checks.py, tofu/data/_class10_compute.py, tofu/data/_class8_compute_signal.py, tofu/tests/tests07_inversions/test_01_isotropic.py
Main changes:
* what was failing for Ti inversions was the method '' used by `scipy.optimize.minimize` (called by `algo4`), it was not iterating
* `method = 'TNC'`, more robust, is used by default now
* Regularized algorithms now work with dconstraints (for radial meshes only)
Also:
* geometry matrix normalization implemented for inversions to reduce risk of numerical errors
* Better handling of errors and better error msg
* Better handling of non-bspline spectral dimensions
Issues:
-------
Fixes, in devel:
* issue #815 
* issue #817
=> More robust algo4 + constraints for regularized algos

tofu/data/_class8_plot.py
Main changes:
* `dx0`, `dx1` where applied only to the `extent` calculations, not to the data itself
* now applied to the x and y data directly, from which `extent` is then derived
Issues:
-------
Fixes, in devel, issue #847
=> dx0, dx1 applied consistently to interactivity in plot_diagnostic()

tofu/data/_class8_equivalent_apertures.py
Main changes:
* Calculation of the centroid of the equivalent aperture did not guarantee that it was inside the polygon
* that is now checked and if not inside, a new sub-routine `_get_centroid()` is called to correct that.
Explanations:
The problem was coming rom the fact that for very curved non-convex equivalent apertures, the polygon centroid is actually not always inside the polygon itself:
After the fix:
Issues:
--------
Fixes, in devel, issue #846
=> [#846] Debugging

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_reverse_ray_tracing.py, tofu/data/_class8_vos.py, tofu/data/_class8_vos_broadband.py, tofu/data/_class8_vos_spectro_nobin_at_lamb.py, tofu/data/_class8_vos_utilities.py
Main changes:
* Minor changes to make `coll.compute_diagnostic_vos_nobin_at_lamb()` more robust
Issues:
--------
Fixes, in devel, issue #874 
Examples:
-----------
Double-checked output of 2 methods to make sure they are comparable
To plot ray tracing from a single point, single wavelength:
```
dout = coll.get_raytracing_from_pts(
ptsx=1.80894181,
ptsy=0.1967529,
ptsz=0,
lamb0=1.55e-10,
n0=100,
n1=100,
plot=True,
plot_config=conf,
)
```
To compute the total contribution of a monochromatic and homogeneous plasma volume (single wavelength, emissivity=1 everywhere):
```
dout = coll.compute_diagnostic_vos_nobin_at_lamb(
key_diag=None,
key_cam=None,
key_mesh='mRZ',
lamb=1.55e-10,
res_RZ=0.02,
res_phi=0.01,
res_rock_curve=None,
n0=100,
n1=100,
nmax_rays=None,
dobin=True, …
```
=> Tools for ray-tracing validation

tofu/spectro/_fit12d_dinput.py
Main changes:
- Replace `debug_binning` arg to `False` in `binning_2d_data()`
=> [#895] _fit12d_dinput.py: set debug_binning arg to False

tofu/data/_class5_compute.py, tofu/data/_class5_plot.py, tofu/data/_class8_reverse_ray_tracing.py, tofu/data/_class8_vos_spectro.py
Main changes:
* `get_crystal_bragglamb()` now return the non-corrected bragg angle by default 
- fixes a double-correction of the bragg angle when doing ray-tracing with a rocking curve
* Changed rocking curve interpolation from nearest neighbor to linear 
Issues:
--------
Fixes, in devel, issue #917 
Examples:
-----------
Before fix:
After:
=> Issue917 rocking curve new

tofu/data/_class2_compute.py, tofu/data/_class8_los_data.py
Main changes:
* `interpolate_along_los(`) now:
- accepts `key_coords='l_from_impact'`
- is more robust vs non-concatenated data
- allows to define all plotting features in `dcolor` (color, linestyle, linewidth, marker...)
- `domain=dict` is operational for `'l_from_impact'` too
Issues:
--------
fixes, in devel, issue #936
=> Better `interpolate_along_los()`: plotting + `'l_from_impact'`

tofu/data/_class8_check.py
Main changes:
* `add_diagnostic()` now displays more detailed error messages when there is an issue with `doptics`, in particular for collimator cameras
Issues:
-------
Fixes, in devel, issue #952
=> Better error msg when defining collimator camera

tofu/data/_class8_check.py
Main changes:
* `add_diagnostic()`:
- was testing all centers of all pixels for `optics` order, even when called for a single pixel in the case of collimator cameras
- now print a more informative warning msg
* no numerical error found
Issues:
--------
Fixes, in devel, issue #956 
Examples:
-----------
It should be noted that the etendue * length overestimates the VOS by a factor 10 because the sensors is 3 times larger than the collimator and analytical etendue formula assumes that the whole pixel is illuminated, which is clearly not the case here, by a factor 9 approximately
=> Optics order checking when creating a `diagnostic`: better warning msg + minor bugfix for `collimator` cameras

tofu/data/_class08_Diagnostic.py, tofu/data/_class08_concatenate_data.py, tofu/data/_class08_get_data.py, tofu/data/_class10_checks.py, tofu/data/_class10_compute.py, tofu/data/_class10_refs.py
Caveat:
--------
Requires `datastock >= 0.0.40` (or `devel` branch post [PR163](https://github.com/ToFuProject/datastock/pull/163))
Main changes:
* Introducing the concept of equivalent diagnostic. Two diagnostics are eqivalent if:
- they have the same number of cameras
- each camera of the first diagnostic can be associated to a camera of the other with eaxctly the same shape (nb. of pixels)
- This is a way of ensuring compatibility of array shapes for matrix operations
* add_inversion(data=...) now accepts data from other diagnostics if they are equivalent
- The reference diagnostic is the one associated to the geometry matrix
- e.g: accepts synthetic data computed by a different diagnostic as long as it is equivalent
Details:
--------
* Most changes occur in …
=> Cross-diag inversions

requirements.txt, setup.py, tofu/data/_class08_Diagnostic.py, tofu/data/_class08_generate_rays.py, tofu/data/_class8_compute.py, tofu/data/_class8_plot_coverage.py, tofu/geom/_vignetting_tools.pxd, tofu/geom/_vignetting_tools.pyx
Main changes:
* `add_rays_from_diagnostic()` implemented
- only for pinhole cameras
- only for non-spectro diags
- only for random strategy
- without vignetting
* Minor cleanup of code:
- more robust `plot_diagnoctic_geometrical_coverage()` vs `key` of diag
- fixed compile-time warning from `nogil` vs `except` 
- Pins `setuptools` to be `!=65.*` and `!=74.*`
* Minor bug fix in vignetting tools on indexing
Issues:
--------
Partially fixes, in devel, issue #973 , but only with random sampling and without vignetting
Fixes, in devel:
* issue #972
* issue #971 
Opens issue #974 
Example:
----------
```
coll.add_rays_from_diagnostic(config=conf)
dax = coll.plot_rays('cup0_cam_rays_random', plot_config=conf)
coll.save_rays_to_stp(key='cup0_cam_rays_random', factor=1000, …
```
=> Issue973 generate rays

tofu/imas2tofu/_comp.py, tofu/imas2tofu/_core.py, tofu/imas2tofu/_mat2ids2calc.py, tofu/nist2tofu/_requests.py, tofu/spectro/_analysis_tools.py, tofu/spectro/_fit12d_dinput.py, tofu/tests/tests01_geom/test_01_GG.py, tofu/utils.py
Main changes:
New strategy for int/ float type checks
```
_NINT = (np.int32, np.int64)
_INT = (int,) + _NINT
_NFLOAT = (np.float32, np.float64)
_FLOAT = (float,) + _NFLOAT
_NUMB = _INT + _FLOAT
```
And always run `isinstance()`
Because the behaviour of `np.int`, `np.int_` or `np.integer` is too dependent on the version of numpy and on the plateform 
Also shows different results depending is using `type()` or `dtype` or `isinstance()`
* `isintance()` allows multiple types and subclasses
* Better to use tuple of all explicit numpy types that resort to generic types
Issues:
-------
Fixes, in devel, issue #983
=> Get rid of `np.int`

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_etendue_los.py, tofu/data/_class8_los_angles.py
Main changes:
* There was an indexing issue in `tofu/data/_class8_los_angles.py`
Fixed by using a tuple of indices:
* `compute_diagnostic_etendue_los(overwrite=bool)` implemented
- Allows to rerun multiple times and overwrite previous results
- mostly useful for debugging
Issues:
-------
Fixes, in devel, issue #984 
Example:
----------
Using the `Collection` instance sent by @cjperks7 , one can now finish the computation of the vos from the los, calling directly the method that does the computation, with overwrite=True (because the original computation could not be carried out).
```
import tofu as tf
conf = tf.load_config('SPARC-V0')
pfe = '/data/home/dvezinet/storage-root/sparc_htpd24_v2_subcamKr.npz'
coll = tf.data.load(pfe)
coll.compute_diagnostic_etendue_los( …
```
=> Issue984 sub cam

tofu/data/_class08_Diagnostic.py, tofu/data/_class8_check.py, tofu/data/_class8_etendue_los.py, tofu/data/_class8_los_angles.py, tofu/data/_class8_vos.py, tofu/data/_class8_vos_broadband.py
Main changes:
* `compute_diagnostic_etendue_los()`:
- `return_dcompute=bool` implemented
- for computing `vos_from_los` now uses sampled pixel AND sampled apertures
* `compute_diagnostic_vos()`:
- `debug=callable` implemented to debug with plots for a single pixel index
- `user_limits={'Dphi': list}` implemented, will use pixel-wise `pcross`
Issues:
-------
Fixes, in devel, issue #993
=> Issue993 dphi pilatus

.github/workflows/test-complete-matrix.yml, pyproject.toml, requirements.txt, setup.py, tofu/geom/_core.py, tofu/tests/tests00_root/test_03_plot.py
Main changes:
* Pinned `setuptools` version to `>=40.8.0, <64` in:
- `seutp.py`
- `requirements.txt`
- `pyproject.toml`
* `<65` is needed to avoid issues with `distutils.msvcompiler`
* `<64` is needed to avoid issues with [loop import in unit tests](https://github.com/ToFuProject/tofu/actions/runs/12141565325/job/33854680422)
Issues:
-------
Hopefully fixes, in devel, issue #951
=> Pinned `setuptools` version to `>=40.8.0, <64`

tofu/data/_class8_los_angles.py, tofu/data/_class8_vos_utilities.py
Main changes:
* Primary issue was actually the computation of `dvos['dphi']` from LOS
- was not handling correctly case with LOS crossing `phi = pi`
- fixed by proper handling of that case (distinguishing between cases)
* In addition, also made `_get_dphi_from_R_phor()` more robust by:
- ensuring `nphi >= 2` by design 
- taking the absolute value of `dphi`
Issues:
--------
Fixes, in devel issue #1000
=> Issue1000 vos broad band

tofu/data/__init__.py, tofu/data/_class00_poly2d_check.py, tofu/data/_class00_poly2d_sample.py, tofu/data/_class08_Diagnostic.py, tofu/data/_class08_generate_rays.py, tofu/data/_class2_check.py, tofu/data/_class8_los_angles.py, tofu/data/_class8_plot.py, tofu/data/_class8_vos.py, tofu/data/_class8_vos_broadband.py, tofu/data/_utils_surface3d.py, tofu/tests/tests08_diagnostics/test_01_diagnostics.py
Main changes:
* `tf.data.poly2d_check()` implemented, for:
- clockwise vs ccw
- closed vs open
- dimensional checks
* `tf.data.poly2d_sample()` implemented, for:
- sampling edge (outline)
- sampling surface
* `add_diagnostic_rays()` implemented, for:
- creating `shape_cam + (nstart, nend)` array of rays for each pixel
- only handle a single optics per pixel so far (user-defined using index)
* Unit tests added for `add_diagnostic_rays()`
* color cycling for LOS fixed
* Better error msg for `add_rays()`
* Minor debug of `user_limits` for `vos` computation
* Minor cleanup of variable names
Issues:
--------
Fixes, in devel, issues:
* #977 
* #1002
=> Issue977:  `add_rays_from_diagnostic()`, `poly2d_check` and `poly2d_sample`, color cycling fixed

tofu/data/_class00_poly2d_sample.py, tofu/data/_class02_Rays.py, tofu/data/_class02_save2stp.py, tofu/data/_class08_generate_rays.py
Main changes:
* `tofu/data/_class00_poly2d_sample.py`:
-  debug `concatenate` vs `ravel`
* `add_rays_from_diagnostic()`:
- `overwrite = bool` implemented
- Better error msg
* `save_rays_to_stp()`
- `chain = 'camera' and 'pixel'` implemented
- `color_by_pixel = float in [0, 1]` implemented 
- now uses `POLYLINE`
Issues:
-------
Fixes, in devel, issue #1005 
Possible improvements on chain by re-using existing `CARTESIAN POINTS` indices instead of duplicating points, cf issue #1012 
Examples:
-----------
Preliminiary (generate rays):
```
coll.add_rays_from_diagnostic(
dsampling_optics={'dedge': {'res': 'min'}, 'dsurface': {'nb': 3}}, 
dsampling_pixel={'dedge': {'res': 'min'}, 'dsurface': {'nb': 3}}, 
optics=-1, 
config=conf, 
store=True, 
overwrite=True,
)
```
Saving …
=> Issue1005 save2stp rays chain

tofu/data/_class02_Rays.py, tofu/data/_class2_sinogram.py, tofu/tests/tests08_diagnostics/test_01_diagnostics.py
Main changes:
* `get_sinogram()` more robust vs multiple solutions:
- check vs `R` (eliminates `R = 0` solutions)
- check vs scalar product (perp vs los)
- check vs Delta phi < `Dphimax` (set to 3pi/4 by default)
Issues:
--------
Fixes, in devel, issue #1026 
Example:
----------
```
runfile('C:/Users/dvezinet/Documents/Projects/tofu_sparc/CVD_Optimization.py', wdir='C:/Users/dvezinet/Documents/Projects/tofu_sparc')
dout, dsin = coll.get_sinogram(R0=1.8, config=conf, ang='xi', impact_pos=False)
```
=> [#1026]  more robust `get_sinogram()`

tofu/data/_class02_save2stp.py
Main changes:
* `save_rays_to_stp(chain=True)` fixed when there is no camera (rays only)
Issues:
-------
Fixes, in devel, issue #1035
=> [#1035] `save_rays_to_stp(chain=True)` fixed for ray only (no camera)

tofu/data/_class02_single_point_camera.py, tofu/data/_class08_interpolate_along_los.py
Main changes:
* Better error msg + safety check in `single_pt_camera()`
* `interpolate_along_los()` more robust
Issues:
--------
Fixes, in devel issue #1111
=> [#1111] Safety check + error msg in single_pt_cam when 1 ray only + better `interpolate_along_los()`
